// src/react/views/aspd-curve.tsx
import { Fragment, createElement, useMemo } from 'react';
import { AspdCurveView } from '../../app/layout/pages/ro-calculator/aspd-curve/aspd-curve.view';
import './aspd-curve.css';

export function AspdCurve({ aspd, aspd2 }: { aspd: number; aspd2?: number | null }) {
  const view = useMemo(() => new AspdCurveView(aspd, aspd2), [aspd, aspd2]);
  return createElement('app-aspd-curve', null, <div className="aspd_curve">
    <svg viewBox={view.viewBox} className="aspd_curve_svg" role="img" aria-label={view.summaryText}>
      {view.yTicks.map(tick => <line key={tick.label} className="curve_grid" x1={view.plotLeft} x2={view.plotRight} y1={tick.y} y2={tick.y} />)}
      <line className="curve_axis" x1={view.plotLeft} x2={view.plotRight} y1={view.plotBottom} y2={view.plotBottom} />
      <line className="curve_axis" x1={view.plotLeft} x2={view.plotLeft} y1={view.plotTop} y2={view.plotBottom} />
      <g className="curve_tick_label">
        {view.yTicks.map(tick => <text key={`y${tick.label}`} x={tick.x - 8} y={tick.y + 4} textAnchor="end">{tick.label}</text>)}
        {view.xTicks.map(tick => <text key={`x${tick.label}`} x={tick.x} y={tick.y + 16} textAnchor="middle">{tick.label}</text>)}
      </g>
      <path className="curve_line" d={view.curvePath} />
      {view.markers.map(marker => <Fragment key={marker.isCompare ? 'compare' : 'main'}>
        <line className={`curve_drop ${marker.isCompare ? 'is_compare' : ''}`} x1={marker.x} x2={marker.x} y1={marker.y} y2={view.plotBottom} />
        {!marker.isCompare && <circle className="curve_dot_halo" cx={marker.x} cy={marker.y} r={9} />}
        <circle className={`curve_dot ${marker.isCompare ? 'is_compare' : ''}`} cx={marker.x} cy={marker.y} r={5} />
        <text className={`curve_dot_label ${marker.isCompare ? 'is_compare' : ''}`} x={marker.labelX} y={marker.labelY} textAnchor={marker.labelAnchor}>{marker.label}</text>
      </Fragment>)}
      <text className="curve_axis_title" x={(view.plotLeft + view.plotRight) / 2} y={view.plotBottom + 32} textAnchor="middle">Vel.Atq</text>
    </svg>
    <div className="curve_legend">
      <span className="curve_legend_item"><i className="swatch swatch_line" />Golpes/s = 50 ÷ (200 − Vel.Atq)</span>
      <span className="curve_legend_item"><i className="swatch swatch_dot" />Sua velocidade de ataque</span>
      {view.markers.length > 1 && <span className="curve_legend_item"><i className="swatch swatch_dot is_compare" />Comparação</span>}
    </div>
    <div className="curve_caption"><div className="curve_caption_main">{view.summaryText}</div><div className="curve_caption_next">{view.gainText}</div></div>
    <table className="curve_table"><caption>Referência: Vel.Atq de cada golpe/s cheio</caption>
      <thead><tr><th scope="col">Golpes/s</th><th scope="col">Vel.Atq</th></tr></thead>
      <tbody>{view.rows.map(row => <tr key={row.aspd} className={row.reached ? 'row_done' : ''}><td>{row.hits}</td><td>{row.aspd}{row.aspd === view.cap ? ' (teto)' : ''}</td></tr>)}</tbody>
    </table>
    <div className="curve_note">A Vel.Atq é hiperbólica: cada ponto vale mais que o anterior, então não há degraus a alcançar — todo ponto rende golpes/s. A tabela é só referência; o teto é {view.cap}.</div>
  </div>);
}

// src/app/layout/pages/ro-calculator/aspd-curve/aspd-curve.component.ts
import { Component, Input, OnChanges } from '@angular/core';
import { ASPD_CAP, engineHitsPerSec, formatNumber, formatRate, hitsPerSecCurve, MAX_HITS_PER_SEC } from '../../../../utils';
import { ASPD_LANDMARKS, AspdLandmark, gainFromAspd } from './aspd-curve.logic';

interface Point {
  x: number;
  y: number;
}

interface Marker extends Point {
  aspd: number;
  label: string;
  /** Label position, flipped to the inside of the frame near the right edge / top. */
  labelX: number;
  labelY: number;
  labelAnchor: 'start' | 'end';
  /** The compared build's marker: same geometry, different colour, no halo. */
  isCompare: boolean;
}

interface AxisTick extends Point {
  label: string;
}

interface LandmarkRow extends AspdLandmark {
  /** Precomputed so the template doesn't call a method on every change-detection pass. */
  reached: boolean;
}

/**
 * The iRO Wiki "Hits per Second" graph (https://irowiki.org/wiki/ASPD#Hits_per_Second)
 * with the current build plotted on it, opened from the "Hits/s" summary value.
 *
 * The curve is what makes VelAtq gear legible: it is a hyperbola, so the marker's
 * position — not its height — tells you whether the next +VelAtq is worth buying. The
 * caption prices that directly (what +10 would buy from here).
 *
 * The SVG is hand-built rather than pulled from a charting library: the domain is fixed
 * and tiny (VelAtq up to 193, 0..7,14 hits/s), and a dependency-free inline SVG inherits
 * the theme's colours and scales with the dialog for free.
 */
@Component({
  selector: 'app-aspd-curve',
  templateUrl: './aspd-curve.component.html',
  styleUrls: ['./aspd-curve.component.css'],
})
export class AspdCurveComponent implements OnChanges {
  @Input({ required: true }) aspd: number;
  /** The compared build's VelAtq, or null when not comparing — plotted as a second marker. */
  @Input() aspd2?: number | null;

  /** SVG user units. The viewBox is fixed; the element scales to the dialog width. */
  private static readonly W = 620;
  private static readonly H = 300;
  private static readonly PAD = { left: 34, right: 30, top: 16, bottom: 34 };
  /** Head-room above the 7,14 hits/s cap so the top marker isn't clipped by the frame. */
  private static readonly Y_MAX = 7.6;

  readonly viewBox = `0 0 ${AspdCurveComponent.W} ${AspdCurveComponent.H}`;
  readonly cap = ASPD_CAP;

  /** Lowest VelAtq on the x axis — see ngOnChanges. */
  private domainMin = 140;

  plotLeft = AspdCurveComponent.PAD.left;
  plotRight = AspdCurveComponent.W - AspdCurveComponent.PAD.right;
  plotTop = AspdCurveComponent.PAD.top;
  plotBottom = AspdCurveComponent.H - AspdCurveComponent.PAD.bottom;

  /** Fixed 1..7 gridlines — they depend on no input, so they're built once. */
  readonly yTicks: AxisTick[] = Array.from({ length: 7 }, (_, i) => ({
    x: this.plotLeft,
    y: this.y(i + 1),
    label: String(i + 1),
  }));

  curvePath = '';
  xTicks: AxisTick[] = [];
  /** Compare marker first so the current build's marker draws on top of it. */
  markers: Marker[] = [];
  rows: LandmarkRow[] = [];
  /** Caption under the chart: where the build sits and what more VelAtq would buy. */
  summaryText = '';
  gainText = '';

  ngOnChanges(): void {
    const aspd = this.clampAspd(this.aspd);
    const aspd2 = this.aspd2 == null ? null : this.clampAspd(this.aspd2);

    // Keep the plotted builds inside the frame: the window normally starts at 140 (below
    // that the curve is flat and uninformative), but drops to a round ten below the
    // lowest marker when a build sits under it.
    const lowest = Math.min(aspd, aspd2 ?? aspd);
    this.domainMin = Math.min(140, Math.floor((lowest - 5) / 10) * 10);

    this.curvePath = this.buildCurvePath();
    this.xTicks = this.buildXTicks();
    this.markers = [
      ...(aspd2 != null && aspd2 !== aspd ? [this.buildMarker(aspd2, true)] : []),
      this.buildMarker(aspd, false),
    ];
    this.rows = ASPD_LANDMARKS.map((l) => ({ ...l, reached: l.aspd <= aspd }));
    this.buildCaption(aspd);
  }

  /** The summary feeds this from an untyped model, so coerce before trusting it. */
  private clampAspd(value: number): number {
    return Math.min(Number(value) || 0, ASPD_CAP);
  }

  private x(aspd: number): number {
    const ratio = (aspd - this.domainMin) / (ASPD_CAP - this.domainMin);
    return this.plotLeft + ratio * (this.plotRight - this.plotLeft);
  }

  private y(hits: number): number {
    const ratio = hits / AspdCurveComponent.Y_MAX;
    return this.plotBottom - ratio * (this.plotBottom - this.plotTop);
  }

  /** One sample per SVG unit of width — enough that the near-vertical tail reads as a curve. */
  private buildCurvePath(): string {
    const steps = Math.round(this.plotRight - this.plotLeft);
    const points: string[] = [];
    for (let i = 0; i <= steps; i++) {
      const aspd = this.domainMin + ((ASPD_CAP - this.domainMin) * i) / steps;
      points.push(`${this.x(aspd).toFixed(1)},${this.y(hitsPerSecCurve(aspd)).toFixed(1)}`);
    }
    return `M${points.join(' L')}`;
  }

  /** Every ten from the domain start, plus the 193 cap. Ticks within 4 of the cap are
   *  dropped so their labels don't overlap it — those VelAtq values are landmarks and
   *  are already labelled in the table below. */
  private buildXTicks(): AxisTick[] {
    const ticks: AxisTick[] = [];
    for (let aspd = Math.ceil(this.domainMin / 10) * 10; aspd <= ASPD_CAP - 4; aspd += 10) {
      ticks.push({ x: this.x(aspd), y: this.plotBottom, label: String(aspd) });
    }
    ticks.push({ x: this.x(ASPD_CAP), y: this.plotBottom, label: String(ASPD_CAP) });
    return ticks;
  }

  /** Positioned on the exact curve, labelled with the rounded rate the engine uses. */
  private buildMarker(aspd: number, isCompare: boolean): Marker {
    const x = this.x(aspd);
    const y = this.y(hitsPerSecCurve(aspd));
    const flip = x > this.plotRight - 110;
    // The compare label sits below its dot so the two never collide when both builds
    // land on nearby VelAtq.
    const above = y < this.plotTop + 16 ? y + 16 : y - 8;
    return {
      x,
      y,
      aspd,
      label: `${aspd} → ${formatRate(engineHitsPerSec(aspd))}/s`,
      labelX: flip ? x - 8 : x + 8,
      labelY: isCompare ? above + 14 : above,
      labelAnchor: flip ? 'end' : 'start',
      isCompare,
    };
  }

  private buildCaption(aspd: number): void {
    this.summaryText = `Vel.Atq ${aspd} → ${formatRate(engineHitsPerSec(aspd))} golpes/s.`;

    const gain = gainFromAspd(aspd);
    if (!gain) {
      this.gainText = `No teto de Vel.Atq (${ASPD_CAP}), o máximo de ${formatRate(MAX_HITS_PER_SEC)} golpes/s.`;
      return;
    }
    // `gain.plus`, not the requested amount: near the cap the increase gets truncated,
    // and promising "+10" for what is really +9 would misprice the last stretch.
    this.gainText =
      `+${gain.plus} de Vel.Atq (chegar a ${gain.aspd}) levaria a ${formatRate(gain.hits)} golpes/s — ` +
      `+${formatRate(gain.delta)}/s, ou +${formatNumber(gain.percent, 0, 1)}% de golpes.`;
  }
}

<div class="aspd_curve">
  <svg [attr.viewBox]="viewBox" class="aspd_curve_svg" role="img" [attr.aria-label]="summaryText">
    <!-- horizontal gridline per whole hit/s -->
    <line *ngFor="let t of yTicks" class="curve_grid" [attr.x1]="plotLeft" [attr.x2]="plotRight" [attr.y1]="t.y" [attr.y2]="t.y" />

    <!-- axes -->
    <line class="curve_axis" [attr.x1]="plotLeft" [attr.x2]="plotRight" [attr.y1]="plotBottom" [attr.y2]="plotBottom" />
    <line class="curve_axis" [attr.x1]="plotLeft" [attr.x2]="plotLeft" [attr.y1]="plotTop" [attr.y2]="plotBottom" />

    <g class="curve_tick_label">
      <text *ngFor="let t of yTicks" [attr.x]="t.x - 8" [attr.y]="t.y + 4" text-anchor="end">{{ t.label }}</text>
      <text *ngFor="let t of xTicks" [attr.x]="t.x" [attr.y]="t.y + 16" text-anchor="middle">{{ t.label }}</text>
    </g>

    <path class="curve_line" [attr.d]="curvePath" />

    <!-- Compare marker first, current build last so it draws on top. -->
    <ng-container *ngFor="let m of markers">
      <line class="curve_drop" [class.is_compare]="m.isCompare" [attr.x1]="m.x" [attr.x2]="m.x" [attr.y1]="m.y" [attr.y2]="plotBottom" />
      <circle *ngIf="!m.isCompare" class="curve_dot_halo" [attr.cx]="m.x" [attr.cy]="m.y" r="9" />
      <circle class="curve_dot" [class.is_compare]="m.isCompare" [attr.cx]="m.x" [attr.cy]="m.y" r="5" />
      <text class="curve_dot_label" [class.is_compare]="m.isCompare" [attr.x]="m.labelX" [attr.y]="m.labelY" [attr.text-anchor]="m.labelAnchor">{{ m.label }}</text>
    </ng-container>

    <text class="curve_axis_title" [attr.x]="(plotLeft + plotRight) / 2" [attr.y]="plotBottom + 32" text-anchor="middle">Vel.Atq</text>
  </svg>

  <div class="curve_legend">
    <span class="curve_legend_item"><i class="swatch swatch_line"></i>Golpes/s = 50 ÷ (200 − Vel.Atq)</span>
    <span class="curve_legend_item"><i class="swatch swatch_dot"></i>Sua velocidade de ataque</span>
    <span class="curve_legend_item" *ngIf="markers.length > 1"><i class="swatch swatch_dot is_compare"></i>Comparação</span>
  </div>

  <div class="curve_caption">
    <div class="curve_caption_main">{{ summaryText }}</div>
    <div class="curve_caption_next">{{ gainText }}</div>
  </div>

  <table class="curve_table">
    <caption>
      Referência: Vel.Atq de cada golpe/s cheio
    </caption>
    <thead>
      <tr>
        <th scope="col">Golpes/s</th>
        <th scope="col">Vel.Atq</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let l of rows" [class.row_done]="l.reached">
        <td>{{ l.hits }}</td>
        <td>{{ l.aspd }}{{ l.aspd === cap ? ' (teto)' : '' }}</td>
      </tr>
    </tbody>
  </table>

  <div class="curve_note">
    A Vel.Atq é hiperbólica: cada ponto vale mais que o anterior, então não há degraus a alcançar — todo ponto rende golpes/s. A tabela é só referência; o teto é
    {{ cap }}.
  </div>
</div>
