// src/react/views/content/item-picker-overlay.tsx
import { Button } from '../../ui/primitives';
import { Fragment } from 'react';
import { Render, displayPipe, interpolate, classNames, normalizeStyle, identityKey } from '../render';
export function Content({vm, services}: {vm: any; services: any}) {
return <>{(() => { const rowTpl = (context: any) => { const row = context["$implicit"];
const i = context["i"]; return <><Render tag="button" props={{"type": "button",
"tabIndex": "-1",
"tooltipPosition": "right",
"tooltipStyleClass": "item_desc_tooltip",
"data-index": i,
"mouseenter": (event: any) => vm.action(() => { const $event = event; vm.hover(i) }),
"click": (event: any) => vm.action(() => { const $event = event; vm.choose(i) }),
"className": ["picker__row",((vm.active === i) ? "picker__row--active" : ''),(vm.isSelected(row) ? "picker__row--selected" : ''),(row.create ? "picker__row--create" : ''),(row.section ? "picker__row--section" : '')].filter(Boolean).join(' '),
"style": normalizeStyle(Object.assign({}, {["height"]: vm.rowHeight == null ? null : String(vm.rowHeight) + "px"})),
"tooltip": {text: (vm.items ? displayPipe("itemDescTooltip", row.value, [vm.items,vm.itemDescriptions.version], services) : ""), position: "right", className: "item_desc_tooltip", showDelay: 350, hideDelay: 0, escape: false, disabled: false}}}>{(() => { const __condition1 = vm.showIcons;  return __condition1 ? <><Render tag="span" props={{"className": ["picker__icon"].filter(Boolean).join(' ')}}>{(() => { const __condition2 = row.icon;  return __condition2 ? <><Render tag="img" props={{"alt": "",
"loading": "lazy",
"src": displayPipe("iconUrl", row.icon, ["item"], services),
"missingIcon": true}}></Render></> : null; })()}</Render></> : null; })()}
<Render tag="span" props={{"className": ["picker__label",(!(!(row.elementClass)) ? "picker__label--tag" : ''),classNames(row.elementClass)].filter(Boolean).join(' ')}}>{interpolate(["",""], [row.label])}</Render>
{(() => { const __condition3 = row.preRelease;  return __condition3 ? <><Render tag="span" props={{"tooltipPosition": "top",
"className": ["pre_release_tag"].filter(Boolean).join(' '),
"tooltip": {text: "Prévia: item ainda não lançado no LATAM — nome e descrição em inglês, do kRO/iRO (divine-pride).", position: "top", className: '', showDelay: 300, hideDelay: 0, escape: true, disabled: false}}}>{"Prévia"}</Render></> : null; })()}
{(() => { const __condition4 = row.group;  return __condition4 ? <><Render tag="span" props={{"className": ["picker__chevron"].filter(Boolean).join(' ')}}>{"›"}</Render></> : null; })()}</Render></>; }; return <><Render tag="div" props={{"tabIndex": "-1",
"appTrapFocus": "",
"appTrapFocusAutoCapture": "",
"keydown": (event: any) => vm.action(() => { const $event = event; vm.onKeyDown($event) }),
"className": ["picker",(vm.virtualise ? "picker--virtual" : '')].filter(Boolean).join(' '),
"style": normalizeStyle(Object.assign({}, {["width"]: vm.pinnedWidth == null ? null : String(vm.pinnedWidth) + "px"}))}}><Render tag="div" props={{"className": ["picker__title"].filter(Boolean).join(' ')}}>{interpolate(["",""], [vm.title])}
{vm.canSearch && <Button icon="search" label="Buscar itens" className="ui-button-text ui-button-sm picker__search"
  onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') event.stopPropagation(); }} onClick={() => vm.action(() => vm.openSearch())} />}</Render>
<Render tag="div" props={{"className": ["picker__filter"].filter(Boolean).join(' ')}}>{(() => { let filter: any = vm["filter"]; return <><Render tag="input" props={{"type": "text",
"data-focus-initial": true,
"placeholder": "Filtrar…",
"value": vm.query,
"input": (event: any) => vm.action(() => { const $event = event; vm.onQuery(filter.value) }),
"className": ["picker__input"].filter(Boolean).join(' '),
"reference": (value: any) => { filter = value; vm["filter"] = value; }}}></Render></>; })()}</Render>
{(() => { const __condition5 = vm.breadcrumb.length;  return __condition5 ? <><Render tag="div" props={{"className": ["picker__crumbs"].filter(Boolean).join(' ')}}><Render tag="button" props={{"type": "button",
"click": (event: any) => vm.action(() => { const $event = event; vm.goToLevel(-(1)) }),
"className": ["picker__crumb"].filter(Boolean).join(' ')}}>{"Todos"}</Render>
{(vm.breadcrumb ?? []).map((__entry6: any, __index6: number, __array6: any[]) => { const node = __entry6;
const i = __index6; return <Fragment key={identityKey(__entry6)}><><Render tag="span" props={{"className": ["picker__crumb-sep"].filter(Boolean).join(' ')}}>{"›"}</Render>
<Render tag="button" props={{"type": "button",
"disabled": (i === (vm.breadcrumb.length - 1)),
"click": (event: any) => vm.action(() => { const $event = event; vm.goToLevel(i) }),
"className": ["picker__crumb"].filter(Boolean).join(' ')}}>{interpolate(["",""], [node.label])}</Render></></Fragment>; })}</Render></> : null; })()}
{(() => { const __condition7 = vm.createKind;  return __condition7 ? <><Render tag="button" props={{"type": "button",
"tabIndex": "-1",
"mouseenter": (event: any) => vm.action(() => { const $event = event; vm.hover(-(2)) }),
"click": (event: any) => vm.action(() => { const $event = event; vm.choose(-(2)) }),
"className": ["picker__row picker__row--create",((vm.active === -(2)) ? "picker__row--active" : '')].filter(Boolean).join(' ')}}><Render tag="span" props={{"className": ["picker__icon"].filter(Boolean).join(' ')}}><Render tag="img" props={{"alt": "",
"src": displayPipe("iconUrl", 512, ["item"], services),
"missingIcon": true}}></Render></Render>
<Render tag="span" props={{"className": ["picker__label"].filter(Boolean).join(' ')}}>{"Criar item personalizado"}</Render></Render></> : null; })()}
{(() => { const __condition8 = vm.clearable;  return __condition8 ? <><Render tag="button" props={{"type": "button",
"tabIndex": "-1",
"mouseenter": (event: any) => vm.action(() => { const $event = event; vm.hover(-(1)) }),
"click": (event: any) => vm.action(() => { const $event = event; vm.choose(-(1)) }),
"className": ["picker__row picker__row--none",((vm.active === -(1)) ? "picker__row--active" : '')].filter(Boolean).join(' ')}}><Render tag="span" props={{"className": ["picker__label picker__label--none"].filter(Boolean).join(' ')}}>{"Nenhum"}</Render></Render></> : null; })()}
{(() => { const __condition9 = (vm.rows.length && vm.virtualise);  return __condition9 ? <><Render tag="app-virtual-list" props={{"items": vm.rows,
"trackBy": vm.trackRow,
"itemSize": vm.rowHeight,
"className": ["picker__list"].filter(Boolean).join(' '),
"style": normalizeStyle(Object.assign({}, {["height"]: vm.viewportHeight == null ? null : String(vm.viewportHeight) + "px"})),
"template_item": (context: any) => { const row = context["$implicit"];
const i = context["index"]; return <>{rowTpl({"$implicit": row,"i": i})}</>; },
"reference": (value: any) => { vm.viewport = value; }}}></Render></> : null; })()}
{(() => { const __condition10 = (vm.rows.length && !(vm.virtualise));  return __condition10 ? <><Render tag="div" props={{"className": ["picker__list picker__list--plain"].filter(Boolean).join(' '),
"style": normalizeStyle(Object.assign({}, {["maxHeight"]: vm.viewportHeight == null ? null : String(vm.viewportHeight) + "px"}))}}>{(vm.rows ?? []).map((__entry11: any, __index11: number, __array11: any[]) => { const row = __entry11;
const i = __index11; return <Fragment key={identityKey(vm.trackRow(__index11, __entry11))}><>{rowTpl({"$implicit": row,"i": i})}</></Fragment>; })}</Render></> : null; })()}
{(() => { const __condition12 = !(vm.rows.length);  return __condition12 ? <><Render tag="div" props={{"className": ["picker__note"].filter(Boolean).join(' ')}}>{"Nada encontrado."}</Render></> : null; })()}
{(() => { const __condition13 = vm.capped;  return __condition13 ? <><Render tag="div" props={{"className": ["picker__note"].filter(Boolean).join(' ')}}>{interpolate(["Mais de "," resultados — refine a busca."], [vm.rows.length])}</Render></> : null; })()}</Render>
</>; })()}</>;
}

// src/app/layout/pages/ro-calculator/item-picker/item-picker-overlay.component.ts
import { CdkVirtualScrollViewport } from '@angular/cdk/scrolling';
import { ChangeDetectionStrategy, ChangeDetectorRef, Component, EventEmitter, Output, ViewChild } from '@angular/core';
import { ItemDescriptionStore } from 'src/app/api-services/item-description.store';
import { filterOptions, searchOptionLeaves } from 'src/app/core/picker-filter';
import { DropdownModel } from 'src/app/models/dropdown.model';
import { ItemModel } from 'src/app/models/item.model';
import { OptionTreeNode, PickerRequest, PickerResult } from './item-picker.model';

/** One rendered line. `group` rows drill into the tree instead of committing. */
interface PickerRow {
  label: string;
  value: string | number | null;
  icon?: string | number | null;
  elementClass?: string;
  preRelease?: boolean;
  group?: boolean;
  children?: readonly OptionTreeNode[];
}

const ROW_HEIGHT = 28;
const MAX_VIEWPORT = 300;
/** Below this the list is short enough that virtualising it only costs a layout pass. */
const SEARCH_LIMIT = 1000;

/**
 * The panel behind every chip in the equipment picker.
 *
 * It replaces a `p-dropdown` (item, card, enchant, refine, grade, ammo, converter,
 * loyalty) or a `p-cascadeSelect` (Bônus Aleatório) — hence the two modes. The keyboard
 * contract is the one people already had from PrimeNG: type to filter, arrows to move,
 * Enter to choose, Esc to close; tree mode adds left/right to walk the breadcrumb.
 */
@Component({
  selector: 'app-item-picker-overlay',
  templateUrl: './item-picker-overlay.component.html',
  styleUrls: ['./item-picker-overlay.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ItemPickerOverlayComponent {
  @Output() readonly closed = new EventEmitter<PickerResult>();

  @ViewChild(CdkVirtualScrollViewport) private viewport?: CdkVirtualScrollViewport;

  request!: PickerRequest;
  query = '';
  /** -1 is the "Nenhum" row, which sits outside the scroller and is always reachable. */
  active = -1;
  rows: PickerRow[] = [];
  capped = false;
  /** Tree mode: the path drilled so far, root first. */
  trail: OptionTreeNode[] = [];

  readonly rowHeight = ROW_HEIGHT;

  constructor(
    private readonly cdr: ChangeDetectorRef,
    public readonly itemDescriptions: ItemDescriptionStore,
  ) {}

  /** Called by the service right after the portal is attached. */
  init(request: PickerRequest): void {
    this.request = request;
    this.query = '';
    this.trail = [];
    this.active = -1;
    this.rebuild();
  }

  get title(): string {
    return this.request?.title ?? '';
  }

  get items(): Record<number, ItemModel> | undefined {
    return this.request?.mode === 'flat' ? this.request.items : undefined;
  }

  get viewportHeight(): number {
    return Math.min(this.rows.length * ROW_HEIGHT, MAX_VIEWPORT);
  }

  /** Tree mode only, and only while browsing — a search has no place in the tree. */
  get breadcrumb(): OptionTreeNode[] {
    return this.request?.mode === 'tree' && !this.query.trim() ? this.trail : [];
  }

  onQuery(value: string): void {
    this.query = value;
    this.active = -1;
    this.rebuild();
  }

  onKeyDown(event: KeyboardEvent): void {
    const last = this.rows.length - 1;

    switch (event.key) {
      case 'Escape':
        this.dismiss();
        return;
      case 'ArrowDown':
        event.preventDefault();
        this.moveTo(Math.min(this.active + 1, last));
        return;
      case 'ArrowUp':
        event.preventDefault();
        this.moveTo(Math.max(this.active - 1, -1));
        return;
      case 'Enter':
        event.preventDefault();
        this.choose(this.active);
        return;
      case 'ArrowRight': {
        const row = this.rows[this.active];
        if (row?.group) {
          event.preventDefault();
          this.choose(this.active);
        }
        return;
      }
      case 'ArrowLeft':
        if (this.canAscend()) {
          event.preventDefault();
          this.ascend();
        }
        return;
      case 'Backspace':
        // Only when the box is empty, so backspacing a typo never jumps a level.
        if (!this.query && this.canAscend()) {
          event.preventDefault();
          this.ascend();
        }
        return;
      default:
        return;
    }
  }

  /** `index` of -1 is the "Nenhum" row. */
  choose(index: number): void {
    if (index < 0) {
      this.closed.emit({ committed: true, value: null });
      return;
    }

    const row = this.rows[index];
    if (!row) return;

    if (row.group) {
      this.descend(row);
      return;
    }

    this.closed.emit({ committed: true, value: row.value });
  }

  hover(index: number): void {
    this.active = index;
  }

  dismiss(): void {
    this.closed.emit({ committed: false });
  }

  /** Jump straight to a level from the breadcrumb; index -1 is the root. */
  goToLevel(index: number): void {
    this.trail = this.trail.slice(0, index + 1);
    this.active = -1;
    this.rebuild();
  }

  isSelected(row: PickerRow): boolean {
    return row.value != null && row.value === this.request?.value;
  }

  private canAscend(): boolean {
    return this.request?.mode === 'tree' && !this.query.trim() && this.trail.length > 0;
  }

  private ascend(): void {
    this.trail = this.trail.slice(0, -1);
    this.active = -1;
    this.rebuild();
  }

  private descend(row: PickerRow): void {
    this.trail = [...this.trail, { label: row.label, value: row.value ?? undefined, children: [...(row.children ?? [])] }];
    this.active = -1;
    this.rebuild();
  }

  private moveTo(index: number): void {
    this.active = index;
    if (index >= 0) this.viewport?.scrollToIndex(index);
  }

  private rebuild(): void {
    this.rows = this.request?.mode === 'tree' ? this.treeRows() : this.flatRows();
    this.cdr.markForCheck();
  }

  private flatRows(): PickerRow[] {
    const request = this.request as Extract<PickerRequest, { mode: 'flat' }>;
    this.capped = false;

    return filterOptions(request.options, this.query, request.filterKeys).map((option: DropdownModel) => ({
      label: option.label,
      value: option.value,
      icon: request.iconKey ? (option[request.iconKey] as string | number) : null,
      elementClass: request.elementColoured && option.element ? `property_${option.element}` : undefined,
      preRelease: !!option['preRelease'],
    }));
  }

  private treeRows(): PickerRow[] {
    const request = this.request as Extract<PickerRequest, { mode: 'tree' }>;
    const term = this.query.trim();

    if (term) {
      // Six thousand leaves are four levels down; searching beats drilling once the
      // reader knows the words.
      const { matches, capped } = searchOptionLeaves(request.leafIndex, term, SEARCH_LIMIT);
      this.capped = capped;
      return matches.map((match) => ({ label: match.label, value: match.value }));
    }

    this.capped = false;
    const level = this.trail.length ? (this.trail[this.trail.length - 1].children ?? []) : request.roots;

    return level.map((node) => ({
      label: node.label,
      value: node.value ?? null,
      group: !!node.children?.length,
      children: node.children,
    }));
  }
}

<!-- The panel traps focus so the arrow keys belong to the list, not to the page behind it.
     Rows are real buttons but stay out of the tab order: the filter box keeps focus and
     drives the list, exactly as the dropdown this replaces did. -->
<div class="picker" tabindex="-1" cdkTrapFocus cdkTrapFocusAutoCapture (keydown)="onKeyDown($event)">
  <div class="picker__title">{{ title }}</div>

  <div class="picker__filter">
    <input
      #filter
      type="text"
      cdkFocusInitial
      class="picker__input"
      placeholder="Filtrar…"
      [value]="query"
      (input)="onQuery(filter.value)"
    />
  </div>

  <div class="picker__crumbs" *ngIf="breadcrumb.length">
    <button type="button" class="picker__crumb" (click)="goToLevel(-1)">Todos</button>
    <ng-container *ngFor="let node of breadcrumb; let i = index">
      <span class="picker__crumb-sep">›</span>
      <button type="button" class="picker__crumb" [disabled]="i === breadcrumb.length - 1" (click)="goToLevel(i)">{{ node.label }}</button>
    </ng-container>
  </div>

  <!-- Outside the scroller so clearing is always one click away, however long the list. -->
  <button
    type="button"
    tabindex="-1"
    class="picker__row picker__row--none"
    [class.picker__row--active]="active === -1"
    (mouseenter)="hover(-1)"
    (click)="choose(-1)"
  >
    <span class="picker__icon">✕</span>
    <span class="picker__label picker__label--none">Nenhum</span>
  </button>

  <cdk-virtual-scroll-viewport
    *ngIf="rows.length"
    class="picker__list"
    [itemSize]="rowHeight"
    [style.height.px]="viewportHeight"
  >
    <button
      *cdkVirtualFor="let row of rows; let i = index"
      type="button"
      tabindex="-1"
      class="picker__row"
      [class.picker__row--active]="active === i"
      [class.picker__row--selected]="isSelected(row)"
      [style.height.px]="rowHeight"
      [pTooltip]="items ? (row.value | itemDescTooltip: items : itemDescriptions.version) : ''"
      [escape]="false"
      tooltipPosition="right"
      [showDelay]="350"
      tooltipStyleClass="item_desc_tooltip"
      (mouseenter)="hover(i)"
      (click)="choose(i)"
    >
      <span class="picker__icon">
        <img *ngIf="row.icon" [src]="row.icon | iconUrl: 'item'" alt="" />
      </span>
      <span class="picker__label" [ngClass]="row.elementClass">{{ row.label }}</span>
      <span *ngIf="row.preRelease" class="pre_release_tag" title="Item ainda não lançado no LATAM — nome e descrição vêm do iRO (divine-pride).">iRO</span>
      <span *ngIf="row.group" class="picker__chevron">›</span>
    </button>
  </cdk-virtual-scroll-viewport>

  <div class="picker__note" *ngIf="!rows.length">Nada encontrado.</div>
  <div class="picker__note" *ngIf="capped">Mais de {{ rows.length }} resultados — refine a busca.</div>
</div>
