// src/app/ui/listbox.component.ts
import { Component, Input, forwardRef } from '@angular/core';
import { NG_VALUE_ACCESSOR } from '@angular/forms';
import { UiValueControl, optionLabel, optionValue, toggleSelection } from './value-control';

@Component({
  selector: 'app-ui-listbox',
  providers: [{ provide: NG_VALUE_ACCESSOR, useExisting: forwardRef(() => UiListboxComponent), multi: true }],
  template: `<div class="ui-listbox ui-component" [ngClass]="styleClass"><div class="ui-listbox-list-wrapper" [ngStyle]="listStyle"><ul class="ui-listbox-list" role="listbox" [attr.aria-label]="ariaLabel || null" [attr.aria-multiselectable]="multiple">
    <li *ngFor="let option of options; let index = index" class="ui-listbox-item" role="option" [attr.aria-selected]="selected(option)" [attr.tabindex]="disabled || option.disabled ? -1 : 0" [class.ui-highlight]="selected(option)" [class.ui-disabled]="disabled || option.disabled" (click)="pick(option, $event)" (keydown)="key(option, $event)">
      <ng-container *ngIf="template('item') as content; else text" [ngTemplateOutlet]="content" [ngTemplateOutletContext]="{ $implicit: option, index: index }"></ng-container><ng-template #text>{{labelOf(option)}}</ng-template>
    </li>
  </ul></div></div>`,
})
export class UiListboxComponent extends UiValueControl {
  @Input() options: any[] = [];
  @Input() multiple = false;
  @Input() metaKeySelection = false;
  @Input() listStyle: Record<string, any> = {};
  @Input() optionLabel = '';
  @Input() optionValue = '';
  labelOf(option: any): string { return optionLabel(option, this.optionLabel); }
  optionValueOf(option: any): any { return optionValue(option, this.optionValue, this.optionLabel); }
  selected(option: any): boolean { const v = this.optionValueOf(option); return this.multiple ? (this.value ?? []).includes(v) : this.value === v; }
  pick(option: any, event: Event): void {
    if (option.disabled) return;
    const value = this.optionValueOf(option);
    const next = this.multiple ? toggleSelection(this.value, value) : this.value === value ? null : value;
    this.commit(next, event);
  }
  key(option: any, event: KeyboardEvent): void {
    if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); this.pick(option, event); }
    if (event.key === 'ArrowDown' || event.key === 'ArrowUp') {
      event.preventDefault(); const element = event.currentTarget as HTMLElement;
      (event.key === 'ArrowDown' ? element.nextElementSibling as HTMLElement : element.previousElementSibling as HTMLElement)?.focus();
    }
  }
}

// src/react/ui/listbox.tsx
import { CSSProperties, KeyboardEvent, ReactNode, SyntheticEvent, createElement } from 'react';
import { optionLabel, optionValue, chooseSelection } from './selection';

export interface ListboxProps {
  options: any[]; value: any;
  onChange: (value: any, event: SyntheticEvent) => void;
  multiple?: boolean; disabled?: boolean; ariaLabel?: string;
  className?: string; listStyle?: CSSProperties;
  optionLabel?: string; optionValue?: string;
  renderItem?: (option: any, index: number) => ReactNode;
}
export function Listbox({ options, value, onChange, multiple = false, disabled = false, ariaLabel,
  className = '', listStyle, optionLabel: labelKey, optionValue: valueKey, renderItem }: ListboxProps) {
  const selected = (option: any) => multiple ? (value ?? []).includes(optionValue(option, valueKey, labelKey)) : value === optionValue(option, valueKey, labelKey);
  const pick = (option: any, event: SyntheticEvent) => {
    if (disabled || option?.disabled) return;
    onChange(chooseSelection(value, option, multiple, true, disabled, valueKey, labelKey), event);
  };
  const key = (option: any, event: KeyboardEvent<HTMLLIElement>) => {
    if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); pick(option, event); }
    if (event.key === 'ArrowDown' || event.key === 'ArrowUp') {
      event.preventDefault();
      (event.key === 'ArrowDown' ? event.currentTarget.nextElementSibling as HTMLElement : event.currentTarget.previousElementSibling as HTMLElement)?.focus();
    }
  };
  return createElement('app-ui-listbox', null, <div className={`ui-listbox ui-component ${className}`}>
    <div className="ui-listbox-list-wrapper" style={listStyle}><ul className="ui-listbox-list" role="listbox" aria-label={ariaLabel} aria-multiselectable={multiple}>
      {options.map((option, index) => <li key={index} className={`ui-listbox-item ${selected(option) ? 'ui-highlight' : ''} ${disabled || option?.disabled ? 'ui-disabled' : ''}`}
        role="option" aria-selected={selected(option)} tabIndex={disabled || option?.disabled ? -1 : 0}
        onClick={event => pick(option, event)} onKeyDown={event => key(option, event)}>
        {renderItem ? renderItem(option, index) : optionLabel(option, labelKey)}
      </li>)}
    </ul></div>
  </div>);
}
