// src/react/ui/dialog.tsx
import { CSSProperties, ReactNode, createElement, useId, useLayoutEffect, useRef, useState } from 'react';
import { Portal } from './portal';
import { Icon } from './primitives';

export interface DialogProps {
  visible: boolean;
  onVisibleChange: (visible: boolean) => void;
  onClosed?: () => void;
  header?: ReactNode;
  footer?: ReactNode;
  children?: ReactNode;
  modal?: boolean;
  closable?: boolean;
  closeOnEscape?: boolean;
  dismissableMask?: boolean;
  style?: CSSProperties;
  contentStyle?: CSSProperties;
  className?: string;
  position?: 'center' | 'top';
}
export function Dialog({ visible, onVisibleChange, onClosed, header = '', footer, children, modal = false,
  closable = true, closeOnEscape = true, dismissableMask = false, style, contentStyle, className = '', position }: DialogProps) {
  const id = useId();
  const [host, setHost] = useState<HTMLElement | null>(null);
  const closed = useRef(onClosed); closed.current = onClosed;
  const lifecycle = useRef<object | null>(null);
  useLayoutEffect(() => {
    if (!visible) return undefined;
    const token = {}; lifecycle.current = token;
    return () => {
      queueMicrotask(() => { if (lifecycle.current === token) closed.current?.(); });
    };
  }, [visible]);
  const close = () => onVisibleChange(false);
  return createElement('app-ui-dialog', { ref: setHost }, visible ? <Portal origin={host} modal={modal} trap={modal} panelClass="ui-dialog-pane" position={position} minWidth={typeof style?.minWidth === 'string' ? parseFloat(style.minWidth) : style?.minWidth}
    onDismiss={close} onEscape={() => { if (closable && closeOnEscape) close(); }}
    onBackdrop={() => { if (dismissableMask) close(); }}>
    <section className={`ui-dialog ui-component ${className}`} style={style} role="dialog" aria-modal={modal} aria-labelledby={id} tabIndex={-1}>
      <div className="ui-dialog-header"><span className={`ui-dialog-title ${typeof header === 'string' ? '' : 'ui-dialog-title-custom'}`} id={id}>{header}</span>
        {closable && <button type="button" className="ui-dialog-header-icon ui-dialog-header-close ui-link" aria-label="Fechar" onClick={close}><Icon name="times" /></button>}
      </div><div className="ui-dialog-content" style={contentStyle}>{children}</div>
      {footer != null && <div className="ui-dialog-footer">{footer}</div>}
    </section>
  </Portal> : null);
}

// src/app/ui/dialog.component.ts
import { AfterViewInit, Component, EventEmitter, Input, OnChanges, OnDestroy, Output, TemplateRef, ViewChild, ViewContainerRef } from '@angular/core';
import { OverlayRef } from 'src/app/ui/overlay';
import { UiTemplated } from './template.directive';
import { UiOverlayService } from './overlay.service';

let dialogId = 0;
@Component({
  selector: 'app-ui-dialog',
  template: `<ng-template #panel>
    <section class="ui-dialog ui-component" [ngClass]="styleClass" [ngStyle]="style" role="dialog" [attr.aria-modal]="modal" [attr.aria-labelledby]="id" tabindex="-1" [appTrapFocus]="modal" [appTrapFocusAutoCapture]="modal">
      <div class="ui-dialog-header"><span class="ui-dialog-title" [class.ui-dialog-title-custom]="template('header')" [id]="id"><ng-container *ngIf="template('header') as content; else title" [ngTemplateOutlet]="content"></ng-container><ng-template #title>{{header}}</ng-template></span>
        <button *ngIf="closable" type="button" class="ui-dialog-header-icon ui-dialog-header-close ui-link" aria-label="Fechar" (click)="close()"><app-icon name="times"></app-icon></button>
      </div>
      <div class="ui-dialog-content" [ngStyle]="contentStyle"><ng-content></ng-content></div>
      <div *ngIf="template('footer') as footer" class="ui-dialog-footer"><ng-container [ngTemplateOutlet]="footer"></ng-container></div>
    </section>
  </ng-template>`,
})
export class UiDialogComponent extends UiTemplated implements AfterViewInit, OnChanges, OnDestroy {
  @Input() visible = false;
  @Input() header = '';
  @Input() modal = false;
  @Input() closable = true;
  @Input() closeOnEscape = true;
  @Input() dismissableMask = false;
  @Input() style: Record<string, any> = {};
  @Input() contentStyle: Record<string, any> = {};
  @Input() styleClass = '';
  @Input() position = 'center';
  @Output() visibleChange = new EventEmitter<boolean>();
  @Output() closed = new EventEmitter<void>();
  @ViewChild('panel', { static: true }) panel!: TemplateRef<any>;
  readonly id = `ui-dialog-title-${++dialogId}`;
  private ref?: OverlayRef;
  private ready = false;
  private destroyed = false;
  constructor(private readonly layers: UiOverlayService, private readonly view: ViewContainerRef) { super(); }
  ngAfterViewInit(): void { this.ready = true; this.sync(); }
  ngOnChanges(): void { this.sync(); }
  private sync(): void {
    if (!this.ready) return;
    if (!this.visible) { this.detach(); return; }
    queueMicrotask(() => {
      if (this.destroyed || !this.visible || this.ref) return;
      const position = this.layers.overlay.position().global().centerHorizontally();
      this.position === 'top' ? position.top('.75rem') : position.centerVertically();
      this.ref = this.layers.open(this.panel, this.view, {
        positionStrategy: position,
        hasBackdrop: this.modal,
        backdropClass: 'ui-dialog-mask',
        panelClass: 'ui-dialog-pane',
        minWidth: this.style['min-width'] ?? this.style['minWidth'],
      }, () => this.close(), true, document.activeElement as HTMLElement,
      () => { if (this.closable && this.closeOnEscape) this.close(); });
      this.ref.backdropClick().subscribe(() => { if (this.dismissableMask) this.close(); });
    });
  }
  close(): void {
    this.visible = false;
    this.visibleChange.emit(false);
    this.detach();
  }
  private detach(): void {
    if (!this.ref) return;
    const ref = this.ref;
    this.ref = undefined;
    this.layers.close(ref);
    this.closed.emit();
  }
  ngOnDestroy(): void { this.destroyed = true; this.detach(); }
}
