// src/react/ui/table.tsx
import { CSSProperties, HTMLAttributes, KeyboardEvent, ReactNode, createElement, useState } from 'react';
import { Icon } from './primitives';
import { tablePage, sameRow } from './table-values';

export interface TableProps<T> {
  value: readonly T[];
  header: ReactNode;
  renderRow: (row: T, index: number, selectionProps: HTMLAttributes<HTMLTableRowElement>) => ReactNode;
  emptyMessage?: ReactNode;
  loading?: boolean;
  className?: string;
  tableStyle?: CSSProperties;
  paginator?: boolean;
  rows?: number;
  first?: number;
  totalRecords?: number;
  pageLinks?: number;
  showCurrentPageReport?: boolean;
  currentPageReportTemplate?: string;
  selection?: T | null;
  dataKey?: keyof T;
  onFirstChange?: (first: number) => void;
  onSelectionChange?: (selection: T | null) => void;
  onRowSelected?: (event: { data: T }) => void;
  onRowUnselected?: (event: { data: T }) => void;
}
export function Table<T>({ value, header, renderRow, emptyMessage, loading = false, className = '', tableStyle,
  paginator = false, rows = 10, first, totalRecords, pageLinks = 5, showCurrentPageReport = false,
  currentPageReportTemplate = '{currentPage} de {totalPages}', selection, dataKey, onFirstChange,
  onSelectionChange, onRowSelected, onRowUnselected }: TableProps<T>) {
  const [localFirst, setLocalFirst] = useState(0);
  const [localSelection, setLocalSelection] = useState<T | null>(null);
  const chosen = selection === undefined ? localSelection : selection;
  const total = totalRecords ?? value.length;
  const { size, pageCount, page, start, displayed, pages } = tablePage(value, rows, first ?? localFirst, paginator, total, pageLinks);
  const fields: Record<string, number> = { totalRecords: total, currentPage: page + 1, totalPages: pageCount,
    first: total ? start + 1 : 0, last: Math.min(total, start + size), rows: size };
  const report = currentPageReportTemplate.replace(/\{(\w+)\}/g, (match, key) => fields[key] == null ? match : String(fields[key]));
  const go = (next: number) => {
    const offset = Math.max(0, Math.min(pageCount - 1, next)) * size;
    setLocalFirst(offset); onFirstChange?.(offset);
  };
  const rowProps = (row: T): HTMLAttributes<HTMLTableRowElement> => {
    const selected = sameRow(chosen, row, dataKey);
    const choose = () => {
      const next = selected ? null : row;
      setLocalSelection(next); onSelectionChange?.(next);
      (selected ? onRowUnselected : onRowSelected)?.({ data: row });
    };
    const key = (event: KeyboardEvent<HTMLTableRowElement>) => {
      if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); choose(); }
      else if (event.key === 'ArrowDown' || event.key === 'ArrowUp') {
        event.preventDefault();
        (event.key === 'ArrowDown' ? event.currentTarget.nextElementSibling as HTMLElement : event.currentTarget.previousElementSibling as HTMLElement)?.focus();
      }
    };
    return { className: `ui-selectable-row ${selected ? 'ui-highlight' : ''}`, tabIndex: 0, 'aria-selected': selected, onClick: choose, onKeyDown: key };
  };
  return createElement('app-ui-table', null, <div className={`ui-datatable ui-component ${className}`} aria-busy={loading}>
    <div className="ui-datatable-wrapper"><table className="ui-datatable-table" style={tableStyle}>
      <thead className="ui-datatable-thead">{header}</thead>
      <tbody className="ui-datatable-tbody">{displayed.map((row, index) => renderRow(row, start + index, rowProps(row)))}{!displayed.length && emptyMessage}</tbody>
    </table></div>
    {loading && <div className="ui-datatable-loading-overlay"><Icon name="spinner" label="Carregando" /></div>}
    {paginator && <nav className="ui-paginator ui-component" aria-label="Paginação">
      {showCurrentPageReport && <span className="ui-paginator-current">{report}</span>}
      <button type="button" className="ui-paginator-first ui-paginator-element ui-link" disabled={page === 0} aria-label="Primeira página" onClick={() => go(0)}><Icon name="angle-double-left" /></button>
      <button type="button" className="ui-paginator-prev ui-paginator-element ui-link" disabled={page === 0} aria-label="Página anterior" onClick={() => go(page - 1)}><Icon name="chevron-left" /></button>
      <span className="ui-paginator-pages">{pages.map(number => <button key={number} type="button" className={`ui-paginator-page ui-paginator-element ui-link ${page === number ? 'ui-highlight' : ''}`}
        aria-current={page === number ? 'page' : undefined} aria-label={`Página ${number + 1}`} onClick={() => go(number)}>{number + 1}</button>)}</span>
      <button type="button" className="ui-paginator-next ui-paginator-element ui-link" disabled={page >= pageCount - 1} aria-label="Próxima página" onClick={() => go(page + 1)}><Icon name="chevron-right" /></button>
      <button type="button" className="ui-paginator-last ui-paginator-element ui-link" disabled={page >= pageCount - 1} aria-label="Última página" onClick={() => go(pageCount - 1)}><Icon name="angle-double-right" /></button>
    </nav>}
  </div>);
}

// src/app/ui/table.component.ts
import { Component, Directive, EventEmitter, HostBinding, HostListener, Input, Output } from '@angular/core';
import { UiTemplated } from './template.directive';

@Component({
  selector: 'app-ui-table',
  template: `<div class="ui-datatable ui-component" [ngClass]="styleClass" [attr.aria-busy]="loading">
    <div class="ui-datatable-wrapper"><table class="ui-datatable-table" [ngStyle]="tableStyle">
      <thead class="ui-datatable-thead"><ng-container [ngTemplateOutlet]="template('header')"></ng-container></thead>
      <tbody class="ui-datatable-tbody"><ng-container *ngFor="let item of displayed; let index = index" [ngTemplateOutlet]="template('body')" [ngTemplateOutletContext]="{ $implicit: item, rowIndex: start + index }"></ng-container>
        <ng-container *ngIf="!displayed.length" [ngTemplateOutlet]="template('emptymessage')"></ng-container>
      </tbody>
    </table></div>
    <div *ngIf="loading" class="ui-datatable-loading-overlay"><app-icon name="spinner" label="Carregando"></app-icon></div>
    <nav *ngIf="paginator" class="ui-paginator ui-component" aria-label="Paginação">
      <span *ngIf="showCurrentPageReport" class="ui-paginator-current">{{report}}</span>
      <button type="button" class="ui-paginator-first ui-paginator-element ui-link" [disabled]="page === 0" aria-label="Primeira página" (click)="go(0)"><app-icon name="angle-double-left"></app-icon></button>
      <button type="button" class="ui-paginator-prev ui-paginator-element ui-link" [disabled]="page === 0" aria-label="Página anterior" (click)="go(page - 1)"><app-icon name="chevron-left"></app-icon></button>
      <span class="ui-paginator-pages"><button *ngFor="let number of pages" type="button" class="ui-paginator-page ui-paginator-element ui-link" [class.ui-highlight]="page === number" [attr.aria-current]="page === number ? 'page' : null" [attr.aria-label]="'Página ' + (number + 1)" (click)="go(number)">{{number + 1}}</button></span>
      <button type="button" class="ui-paginator-next ui-paginator-element ui-link" [disabled]="page >= pageCount - 1" aria-label="Próxima página" (click)="go(page + 1)"><app-icon name="chevron-right"></app-icon></button>
      <button type="button" class="ui-paginator-last ui-paginator-element ui-link" [disabled]="page >= pageCount - 1" aria-label="Última página" (click)="go(pageCount - 1)"><app-icon name="angle-double-right"></app-icon></button>
    </nav>
  </div>`,
})
export class UiTableComponent extends UiTemplated {
  @Input() value: any[] = [];
  @Input() loading = false;
  @Input() styleClass = '';
  @Input() tableStyle: Record<string, any> = {};
  @Input() paginator = false;
  @Input() rows = 10;
  @Input() first = 0;
  @Input() totalRecords?: number;
  @Input() pageLinks = 5;
  @Input() showCurrentPageReport = false;
  @Input() currentPageReportTemplate = '{currentPage} de {totalPages}';
  @Input() selectionMode = '';
  @Input() selection: any;
  @Input() dataKey = '';
  @Output() firstChange = new EventEmitter<number>();
  @Output() selectionChange = new EventEmitter<any>();
  @Output() rowSelected = new EventEmitter<{ data: any }>();
  @Output() rowUnselected = new EventEmitter<{ data: any }>();
  get total(): number { return this.totalRecords ?? this.value?.length ?? 0; }
  get pageCount(): number { return Math.max(1, Math.ceil(this.total / this.rows)); }
  get page(): number { return Math.max(0, Math.min(this.pageCount - 1, Math.floor(this.first / this.rows))); }
  get start(): number { return this.paginator ? this.page * this.rows : 0; }
  get displayed(): any[] { return this.paginator ? (this.value ?? []).slice(this.start, this.start + this.rows) : this.value ?? []; }
  get pages(): number[] { const start = Math.max(0, Math.min(this.page - Math.floor(this.pageLinks / 2), this.pageCount - this.pageLinks)); return Array.from({ length: Math.min(this.pageLinks, this.pageCount) }, (_, i) => start + i); }
  get report(): string {
    const fields = { totalRecords: this.total, currentPage: this.page + 1, totalPages: this.pageCount, first: this.total ? this.start + 1 : 0, last: Math.min(this.total, this.start + this.rows), rows: this.rows };
    return this.currentPageReportTemplate.replace(/\{(\w+)\}/g, (match, key) => fields[key] == null ? match : String(fields[key]));
  }
  go(page: number): void { this.first = Math.max(0, Math.min(this.pageCount - 1, page)) * this.rows; this.firstChange.emit(this.first); }
  selected(row: any): boolean { return this.selection === row || !!this.dataKey && this.selection != null && this.selection[this.dataKey] === row?.[this.dataKey]; }
  choose(row: any): void {
    const selected = this.selected(row);
    this.selection = selected ? null : row;
    this.selectionChange.emit(this.selection);
    (selected ? this.rowUnselected : this.rowSelected).emit({ data: row });
  }
}

@Directive({ selector: '[appSelectableRow]' })
export class UiSelectableRowDirective {
  @HostBinding('class.ui-selectable-row') readonly rowClass = true;
  @HostBinding('attr.tabindex') readonly tabindex = 0;
  @Input('appSelectableRow') row: any;
  constructor(private readonly table: UiTableComponent) {}
  @HostBinding('class.ui-highlight') get selected(): boolean { return this.table.selected(this.row); }
  @HostBinding('attr.aria-selected') get ariaSelected(): boolean { return this.selected; }
  @HostListener('click') click(): void { this.table.choose(this.row); }
  @HostListener('keydown', ['$event']) key(event: KeyboardEvent): void {
    if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); this.click(); }
    else if (event.key === 'ArrowDown' || event.key === 'ArrowUp') {
      event.preventDefault(); const row = event.currentTarget as HTMLElement;
      (event.key === 'ArrowDown' ? row.nextElementSibling as HTMLElement : row.previousElementSibling as HTMLElement)?.focus();
    }
  }
}
