// src/react/ui/virtual-list.tsx
import { CSSProperties, ReactNode, Ref, createElement, useImperativeHandle, useLayoutEffect, useRef, useState } from 'react';
import { virtualRange } from './selection';

export interface VirtualListHandle { scrollToIndex(index: number): void; }
export interface VirtualListProps<T> {
  items: readonly T[];
  itemSize?: number;
  height: number;
  className?: string;
  id?: string;
  role?: string;
  multiselectable?: boolean;
  getKey?: (item: T, index: number) => string | number;
  renderItem: (item: T, index: number) => ReactNode;
  ref?: Ref<VirtualListHandle>;
}
export function VirtualList<T>({ items, itemSize = 28, height, className = '', id, role, multiselectable,
  getKey, renderItem, ref }: VirtualListProps<T>) {
  const host = useRef<HTMLDivElement>(null);
  const [scrollTop, setScrollTop] = useState(0);
  const [measuredHeight, setMeasuredHeight] = useState(height);
  const size = Math.max(1, itemSize);
  useLayoutEffect(() => {
    const element = host.current!;
    const refresh = () => {
      element.scrollTop = Math.min(element.scrollTop, Math.max(0, items.length * size - element.clientHeight));
      setScrollTop(element.scrollTop);
      setMeasuredHeight(element.clientHeight || height);
    };
    const observer = new ResizeObserver(refresh);
    observer.observe(element);
    refresh();
    return () => observer.disconnect();
  }, [items.length, size, height]);
  useImperativeHandle(ref, () => ({ scrollToIndex(index) {
    const element = host.current!;
    const top = Math.max(0, Math.min(items.length - 1, index)) * size;
    if (top < element.scrollTop) element.scrollTop = top;
    else if (top + size > element.scrollTop + element.clientHeight) element.scrollTop = top + size - element.clientHeight;
    setScrollTop(element.scrollTop);
  } }), [items.length, size]);
  const { start, end } = virtualRange(items.length, size, measuredHeight, scrollTop);
  const style: CSSProperties = { height, display: 'block', position: 'relative', overflow: 'auto', contain: 'strict', overflowAnchor: 'none' };
  return createElement('app-virtual-list', { ref: host, className, id, role, 'aria-multiselectable': multiselectable,
    style, onScroll: (event: React.UIEvent<HTMLElement>) => setScrollTop(event.currentTarget.scrollTop) }, <>
    <div className="ui-virtual-spacer" style={{ height: items.length * size }} />
    <div className="ui-virtual-content" style={{ transform: `translateY(${start * size}px)` }}>
      {items.slice(start, end).map((item, offset) => <div key={getKey?.(item, start + offset) ?? start + offset} style={{ height: size }}>{renderItem(item, start + offset)}</div>)}
    </div>
  </>);
}

// src/app/ui/virtual-list.component.ts
import { AfterViewInit, ChangeDetectionStrategy, ChangeDetectorRef, Component, ContentChild, ElementRef, HostListener, Input, OnChanges, OnDestroy, TemplateRef } from '@angular/core';

export function virtualRange(count: number, itemSize: number, height: number, scrollTop: number, overscan = 4): { start: number; end: number } {
  const first = Math.floor(Math.max(0, scrollTop) / Math.max(1, itemSize));
  return { start: Math.min(count, Math.max(0, first - overscan)), end: Math.min(count, first + Math.ceil(height / Math.max(1, itemSize)) + overscan) };
}
@Component({
  selector: 'app-virtual-list',
  template: `<div class="ui-virtual-spacer" [style.height.px]="items.length * itemSize"></div><div class="ui-virtual-content" [style.transform]="'translateY(' + start * itemSize + 'px)'"><ng-container *ngFor="let row of visible; let offset = index; trackBy: track"><ng-container [ngTemplateOutlet]="rowTemplate" [ngTemplateOutletContext]="{ $implicit: row, index: start + offset }"></ng-container></ng-container></div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class VirtualListComponent implements AfterViewInit, OnChanges, OnDestroy {
  @Input() items: any[] = [];
  @Input() itemSize = 28;
  @Input() trackBy: (index: number, item: any) => any = (_index, item) => item;
  @ContentChild(TemplateRef, { static: true }) rowTemplate!: TemplateRef<any>;
  start = 0; visible: any[] = [];
  private observer?: ResizeObserver;
  constructor(private readonly element: ElementRef<HTMLElement>, private readonly change: ChangeDetectorRef) {}
  track = (offset: number, item: any) => this.trackBy(this.start + offset, item);
  ngOnChanges(): void { this.refresh(); }
  ngAfterViewInit(): void {
    this.observer = new ResizeObserver(() => { this.refresh(); this.change.detectChanges(); });
    this.observer.observe(this.element.nativeElement);
    this.refresh(); this.change.detectChanges();
  }
  @HostListener('scroll') refresh(): void {
    const host = this.element.nativeElement;
    const maximum = Math.max(0, this.items.length * this.itemSize - host.clientHeight);
    if (host.scrollTop > maximum) host.scrollTop = maximum;
    const range = virtualRange(this.items.length, this.itemSize, host.clientHeight || parseFloat(host.style.height) || 300, host.scrollTop);
    this.start = range.start;
    this.visible = this.items.slice(range.start, range.end);
    this.change.markForCheck();
  }
  scrollToIndex(index: number): void {
    const host = this.element.nativeElement;
    const top = Math.max(0, Math.min(this.items.length - 1, index)) * this.itemSize;
    if (top < host.scrollTop) host.scrollTop = top;
    else if (top + this.itemSize > host.scrollTop + host.clientHeight) host.scrollTop = top + this.itemSize - host.clientHeight;
    this.refresh(); this.change.detectChanges();
  }
  ngOnDestroy(): void { this.observer?.disconnect(); }
}
