// src/app/layout/pages/ro-calculator/battle-hud/rotation-timeline/rotation-timeline.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { RotationCycle } from '../../../../../core/rotation-schedule';
import { BASIC_ATTACK_ICON } from '../rotation-list/rotation-list.component';
import { RotationEntryView } from '../rotation-view';
import { buildTimelineCharts, TimelineChart } from './rotation-timeline.logic';

/**
 * The cycle flowchart: one lane per rotation entry on a shared time axis.
 *
 * Built from positioned divs rather than the hand-rolled SVG that aspd-curve uses. The
 * lanes are percentage-positioned blocks carrying in-block numeric labels, hover
 * tooltips, dashed borders and a 45° hatch — all of which CSS does for free and SVG
 * would need hand-laid text for. The file layout still follows aspd-curve: a dumb
 * component over a pure, tested `.logic.ts`.
 */
@Component({
  selector: 'app-rotation-timeline',
  templateUrl: './rotation-timeline.component.html',
  styleUrls: ['./rotation-timeline.component.css'],
})
export class RotationTimelineComponent {
  @Input({ required: true }) cycle!: RotationCycle;
  @Input({ required: true }) entries: RotationEntryView[] = [];
  @Input() cycle2: RotationCycle | null = null;
  @Input() entries2: RotationEntryView[] | null = null;

  /**
   * A lane icon was clicked. The index is the lane's position, which is the rotation
   * entry's own index — both charts are built from the same ordered entries, so a lane in
   * the comparison chart names the same step as the one above it.
   */
  @Output() iconClick = new EventEmitter<{ index: number; event: Event }>();

  readonly basicAttackIcon = BASIC_ATTACK_ICON;

  get charts(): TimelineChart[] {
    if (!this.cycle) return [];

    const shape = (cycle: RotationCycle, entries: RotationEntryView[]) => ({
      cycle,
      entries: entries.map((e) => ({
        name: e.name,
        icon: e.icon,
        isBasic: e.isBasic,
        cast: e.summary?.calcSkill?.castPeriod ?? 0,
        // The fixed half of the cast, so the lane can show fixa and variável apart.
        fixed: e.isBasic ? 0 : e.summary?.calcSkill?.reducedFct ?? 0,
      })),
    });

    return buildTimelineCharts({
      current: shape(this.cycle, this.entries),
      compare: this.cycle2 ? shape(this.cycle2, this.entries2 ?? []) : null,
    });
  }

  trackByIndex(index: number): number {
    return index;
  }
}

<!--
  The lane icons are popover triggers, made keyboard-operable by the shared keyActivate
  directive, which the a11y template rule cannot see.
-->
<!-- eslint-disable @angular-eslint/template/click-events-have-key-events -->

<div class="tl">
  <div class="tl-chart" *ngFor="let chart of charts; let ci = index; trackBy: trackByIndex" [class.tl-chart--cmp]="chart.isCompare">
    <div class="tl-title" *ngIf="chart.title" [class.tl-title--cmp]="chart.isCompare">{{ chart.title }}</div>

    <div class="tl-lane-row" *ngFor="let lane of chart.lanes; let li = index; trackBy: trackByIndex">
      <img
        class="tl-icon"
        *ngIf="lane.isBasic"
        [src]="basicAttackIcon"
        [alt]="lane.name"
        role="button"
        tabindex="0"
        keyActivate
        pTooltip="Detalhes da habilidade"
        tooltipPosition="top"
        (click)="iconClick.emit({ index: li, event: $event })"
      />
      <img
        class="tl-icon"
        *ngIf="!lane.isBasic"
        [src]="lane.icon | iconUrl: 'skill'"
        [alt]="lane.name"
        missingSkillIcon
        role="button"
        tabindex="0"
        keyActivate
        pTooltip="Detalhes da habilidade"
        tooltipPosition="top"
        (click)="iconClick.emit({ index: li, event: $event })"
      />

      <div class="tl-track" [class.tl-track--invalid]="lane.invalid">
        <div
          *ngFor="let block of lane.blocks; trackBy: trackByIndex"
          class="tl-block"
          [ngClass]="'tl-block--' + block.kind"
          [class.tl-block--full]="block.isFullHeight"
          [style.left.%]="block.leftPercent"
          [style.width.%]="block.widthPercent"
          [pTooltip]="block.tooltip"
          tooltipPosition="top"
        >
          <span class="tl-block-label" *ngIf="block.label">{{ block.label }}</span>
        </div>
      </div>
    </div>

    <div class="tl-axis">
      <span
        *ngFor="let tick of chart.ticks; trackBy: trackByIndex"
        class="tl-tick"
        [class.tl-tick--end]="tick.isCycleEnd"
        [ngClass]="'tl-anchor-' + tick.anchor"
        [style.left.%]="tick.leftPercent"
        >{{ tick.label }}</span
      >
    </div>
  </div>

  <div class="tl-legend">
    <span class="tl-key"><i class="tl-sw tl-sw--fixa"></i>Conj. fixa</span>
    <span class="tl-key"><i class="tl-sw tl-sw--variavel"></i>Conj. variável</span>
    <span class="tl-key"><i class="tl-sw tl-sw--pos"></i>Pós-conjuração</span>
    <span class="tl-key"><i class="tl-sw tl-sw--recarga"></i>Recarga</span>
    <span class="tl-key"><i class="tl-sw tl-sw--aspd"></i>Espera por VelAtq</span>
  </div>

  <p class="tl-note" *ngIf="charts.length > 1">
    Os dois gráficos são completos e independentes: mesma escala de tempo, cada um com o seu próprio marcador de fim de ciclo.
  </p>
</div>

// src/react/views/content/rotation-timeline.tsx
import { Fragment } from 'react';
import { Render, displayPipe, interpolate, classNames, normalizeStyle, identityKey } from '../render';
export function Content({vm, services}: {vm: any; services: any}) {
return <><Render tag="div" props={{"className": ["tl"].filter(Boolean).join(' ')}}>{(vm.charts ?? []).map((__entry1: any, __index1: number, __array1: any[]) => { const chart = __entry1;
const ci = __index1; return <Fragment key={identityKey(vm.trackByIndex(__index1, __entry1))}><Render tag="div" props={{"className": ["tl-chart",(chart.isCompare ? "tl-chart--cmp" : '')].filter(Boolean).join(' ')}}>{(() => { const __condition2 = chart.title;  return __condition2 ? <><Render tag="div" props={{"className": ["tl-title",(chart.isCompare ? "tl-title--cmp" : '')].filter(Boolean).join(' ')}}>{interpolate(["",""], [chart.title])}</Render></> : null; })()}
{(chart.lanes ?? []).map((__entry3: any, __index3: number, __array3: any[]) => { const lane = __entry3;
const li = __index3; return <Fragment key={identityKey(vm.trackByIndex(__index3, __entry3))}><Render tag="div" props={{"className": ["tl-lane-row"].filter(Boolean).join(' ')}}>{(() => { const __condition4 = lane.isBasic;  return __condition4 ? <><Render tag="img" props={{"role": "button",
"tabIndex": "0",
"tooltipPosition": "top",
"src": vm.basicAttackIcon,
"alt": lane.name,
"click": (event: any) => vm.action(() => { const $event = event; vm.iconClick.emit({"index": li,"event": $event}) }),
"className": ["tl-icon"].filter(Boolean).join(' '),
"tooltip": {text: "Detalhes da habilidade", position: "top", className: '', showDelay: 0, hideDelay: 0, escape: true, disabled: false},
"activateWithKeys": true}}></Render></> : null; })()}
{(() => { const __condition5 = !(lane.isBasic);  return __condition5 ? <><Render tag="img" props={{"role": "button",
"tabIndex": "0",
"tooltipPosition": "top",
"src": displayPipe("iconUrl", lane.icon, ["skill"], services),
"alt": lane.name,
"click": (event: any) => vm.action(() => { const $event = event; vm.iconClick.emit({"index": li,"event": $event}) }),
"className": ["tl-icon"].filter(Boolean).join(' '),
"tooltip": {text: "Detalhes da habilidade", position: "top", className: '', showDelay: 0, hideDelay: 0, escape: true, disabled: false},
"activateWithKeys": true,
"missingIcon": true}}></Render></> : null; })()}
<Render tag="div" props={{"className": ["tl-track",(lane.invalid ? "tl-track--invalid" : '')].filter(Boolean).join(' ')}}>{(lane.blocks ?? []).map((__entry6: any, __index6: number, __array6: any[]) => { const block = __entry6; return <Fragment key={identityKey(vm.trackByIndex(__index6, __entry6))}><Render tag="div" props={{"tooltipPosition": "top",
"className": ["tl-block",classNames(("tl-block--" + block.kind)),(block.isFullHeight ? "tl-block--full" : '')].filter(Boolean).join(' '),
"style": normalizeStyle(Object.assign({}, {["left"]: block.leftPercent == null ? null : String(block.leftPercent) + "%"},{["width"]: block.widthPercent == null ? null : String(block.widthPercent) + "%"})),
"tooltip": {text: block.tooltip, position: "top", className: '', showDelay: 0, hideDelay: 0, escape: true, disabled: false}}}>{(() => { const __condition7 = block.label;  return __condition7 ? <><Render tag="span" props={{"className": ["tl-block-label"].filter(Boolean).join(' ')}}>{interpolate(["",""], [block.label])}</Render></> : null; })()}</Render></Fragment>; })}</Render></Render></Fragment>; })}
<Render tag="div" props={{"className": ["tl-axis"].filter(Boolean).join(' ')}}>{(chart.ticks ?? []).map((__entry8: any, __index8: number, __array8: any[]) => { const tick = __entry8; return <Fragment key={identityKey(vm.trackByIndex(__index8, __entry8))}><Render tag="span" props={{"className": ["tl-tick",(tick.isCycleEnd ? "tl-tick--end" : ''),classNames(("tl-anchor-" + tick.anchor))].filter(Boolean).join(' '),
"style": normalizeStyle(Object.assign({}, {["left"]: tick.leftPercent == null ? null : String(tick.leftPercent) + "%"}))}}>{interpolate(["",""], [tick.label])}</Render></Fragment>; })}</Render></Render></Fragment>; })}
<Render tag="div" props={{"className": ["tl-legend"].filter(Boolean).join(' ')}}><Render tag="span" props={{"className": ["tl-key"].filter(Boolean).join(' ')}}><Render tag="i" props={{"className": ["tl-sw tl-sw--fixa"].filter(Boolean).join(' ')}}></Render>
{"Conj. fixa"}</Render>
<Render tag="span" props={{"className": ["tl-key"].filter(Boolean).join(' ')}}><Render tag="i" props={{"className": ["tl-sw tl-sw--variavel"].filter(Boolean).join(' ')}}></Render>
{"Conj. variável"}</Render>
<Render tag="span" props={{"className": ["tl-key"].filter(Boolean).join(' ')}}><Render tag="i" props={{"className": ["tl-sw tl-sw--pos"].filter(Boolean).join(' ')}}></Render>
{"Pós-conjuração"}</Render>
<Render tag="span" props={{"className": ["tl-key"].filter(Boolean).join(' ')}}><Render tag="i" props={{"className": ["tl-sw tl-sw--recarga"].filter(Boolean).join(' ')}}></Render>
{"Recarga"}</Render>
<Render tag="span" props={{"className": ["tl-key"].filter(Boolean).join(' ')}}><Render tag="i" props={{"className": ["tl-sw tl-sw--aspd"].filter(Boolean).join(' ')}}></Render>
{"Espera por Vel.Atq"}</Render></Render>
{(() => { const __condition9 = (vm.charts.length > 1);  return __condition9 ? <><Render tag="p" props={{"className": ["tl-note"].filter(Boolean).join(' ')}}>{" Os dois gráficos são completos e independentes: mesma escala de tempo, cada um com o seu próprio marcador de fim de ciclo. "}</Render></> : null; })()}</Render></>;
}
