// src/react/views/content/help-improve-dialog.tsx
import { Fragment } from 'react';
import { Render, interpolate, parseStyle, normalizeStyle, identityKey } from '../render';
export function Content({vm, services}: {vm: any; services: any}) {
return <><Render tag="app-ui-dialog" props={{"visible": vm.visible,
"modal": true,
"contentStyle": {"maxHeight": "75vh"},
"visibleChange": (event: any) => vm.action(() => { const $event = event; (!($event) && vm.onHide()) }),
"style": normalizeStyle(Object.assign({}, normalizeStyle(vm.dialogStyle))),
"template_header": (context: any) => {  return <><Render tag="div" props={{"className": ["flex align-items-center gap-2"].filter(Boolean).join(' ')}}><Render tag="app-icon" props={{"name": "heart-fill",
"className": ["text-xl"].filter(Boolean).join(' ')}}></Render>
<Render tag="span" props={{"className": ["text-xl font-medium"].filter(Boolean).join(' ')}}>{"Ajude o simulador a acertar as contas"}</Render></Render></>; },
"template_footer": (context: any) => {  return <><Render tag="div" props={{"className": ["flex align-items-center justify-content-end w-full"].filter(Boolean).join(' ')}}><Render tag="button" props={{"label": "Fechar",
"click": (event: any) => vm.action(() => { const $event = event; vm.onHide() }),
"className": ["ui-button-text"].filter(Boolean).join(' '),
"button": true}}></Render></Render></>; }}}>
<Render tag="p" props={{"className": ["mt-0 line-height-3"].filter(Boolean).join(' ')}}>{" Cada fórmula daqui é conferida contra o jogo de verdade: pegamos uma "}
<Render tag="b" props={{}}>{"gravação"}</Render>
{" sua, lemos os pacotes de dano um por um e comparamos com o que o simulador calcula. Quando um número não bate, é assim que o erro aparece — e é assim que ele é corrigido. "}</Render>
<Render tag="p" props={{"className": ["line-height-3"].filter(Boolean).join(' ')}}>{" Esta primeira etapa tem um alvo específico: "}
<Render tag="b" props={{}}>{"achar itens cadastrados errados e fórmulas erradas"}</Render>
{". Para isso a gravação precisa ser "}
<Render tag="b" props={{}}>{"limpa"}</Render>
{" — só assim dá para saber se a diferença veio do item ou da conta. Por isso duas regras são obrigatórias, e o envio é recusado sem elas: "}</Render>
<Render tag="div" props={{"className": ["flex align-items-start gap-2 mb-3 p-3 border-round"].filter(Boolean).join(' '),
"style": normalizeStyle(Object.assign({}, parseStyle("background: var(--yellow-100); color: var(--yellow-900)")))}}><Render tag="app-icon" props={{"name": "exclamation-triangle",
"className": ["mt-1"].filter(Boolean).join(' ')}}></Render>
<Render tag="div" props={{"className": ["line-height-3"].filter(Boolean).join(' ')}}><Render tag="b" props={{}}>{"1. No campo de treinamento"}</Render>
{" ("}
<Render tag="code" props={{}}>{"tra_fild"}</Render>
{"), "}
<Render tag="b" props={{}}>{"batendo nos dummies"}</Render>
{". Os dummies têm DEF e RES zeradas, ficam parados e não revidam — é o único alvo cujos números são todos conhecidos. Em qualquer outro lugar o monstro tem defesas próprias e a conta passa a ter duas incógnitas ao mesmo tempo."}
<Render tag="br" props={{}}></Render>
<Render tag="b" props={{}}>{"2. Sem buffs de fora."}</Render>
{" Nada de Bênção, Agilidade, Bragi, Poema, comidas ou buffs de outro jogador. Eles inflam todos os números sem dizer em que etapa entraram, e foi exatamente o que inutilizou a primeira leva de gravações. Seus próprios bônus de equipamento e as habilidades da sua classe, sim — é isso que está sendo medido. "}</Render></Render>
<Render tag="p" props={{"className": ["line-height-3"].filter(Boolean).join(' ')}}>{" Gravar leva uns "}
<Render tag="b" props={{}}>{"10 minutos"}</Render>
{" e ajuda principalmente as classes menos testadas. Se a sua gravação levar a alguma correção, seu nome entra nas Novidades. "}</Render>
<Render tag="app-ui-accordion" props={{}}><Render tag="app-ui-accordion-tab" props={{"header": "1. Como abrir o gravador"}}><Render tag="ul" props={{"className": ["mt-0 line-height-3"].filter(Boolean).join(' ')}}><Render tag="li" props={{}}>{"O gravador fica num botão dentro da "}
<Render tag="b" props={{}}>{"janela de informações do personagem"}</Render>
{"."}</Render>
<Render tag="li" props={{}}>{"Ele tem os botões "}
<Render tag="b" props={{}}>{"Início/Fim"}</Render>
{", "}
<Render tag="b" props={{}}>{"Pausa"}</Render>
{" e "}
<Render tag="b" props={{}}>{"Opções"}</Render>
{"."}</Render>
<Render tag="li" props={{}}>{"É preciso dar um "}
<Render tag="b" props={{}}>{"nome"}</Render>
{" ao vídeo antes de gravar."}</Render>
<Render tag="li" props={{}}>{"O arquivo sai em "}
<Render tag="b" props={{}}>{".rrf"}</Render>
{", na pasta "}
<Render tag="b" props={{}}>{"Replay"}</Render>
{" de onde o jogo está instalado."}</Render></Render>
<Render tag="a" props={{"target": "_blank",
"rel": "noreferrer noopener",
"href": vm.browikiUrl}}>{"Passo a passo completo no bROWiki →"}</Render></Render>
<Render tag="app-ui-accordion-tab" props={{"header": "2. Antes de apertar Início — confira as Opções"}}><Render tag="div" props={{"className": ["flex align-items-start gap-2 mb-3 p-2 border-round"].filter(Boolean).join(' '),
"style": normalizeStyle(Object.assign({}, parseStyle("background: var(--yellow-100); color: var(--yellow-900)")))}}><Render tag="app-icon" props={{"name": "exclamation-triangle",
"className": ["mt-1"].filter(Boolean).join(' ')}}></Render>
<Render tag="div" props={{"className": ["line-height-3"].filter(Boolean).join(' ')}}>{" A caixa "}
<Render tag="b" props={{}}>{"Skill"}</Render>
{" é o que põe a "}
<Render tag="b" props={{}}>{"árvore de habilidades"}</Render>
{" dentro do arquivo — sem ela não dá para conferir nada, e o envio é recusado. As caixas só podem ser mexidas "}
<Render tag="b" props={{}}>{"antes"}</Render>
{" de começar a gravar. "}</Render></Render>
<Render tag="ul" props={{"className": ["mt-0 line-height-3"].filter(Boolean).join(' ')}}><Render tag="li" props={{}}>{"Marque "}
<Render tag="b" props={{}}>{"Basic Info"}</Render>
{", "}
<Render tag="b" props={{}}>{"Equip"}</Render>
{", "}
<Render tag="b" props={{}}>{"Item"}</Render>
{" e "}
<Render tag="b" props={{}}>{"Skill"}</Render>
{" — o mais fácil é marcar "}
<Render tag="b" props={{}}>{"All"}</Render>
{"."}</Render>
<Render tag="li" props={{}}><Render tag="b" props={{}}>{"Privacidade:"}</Render>
{" com "}
<Render tag="b" props={{}}>{"Chatting"}</Render>
{" marcado, a gravação leva junto o chat público e as "}
<Render tag="b" props={{}}>{"conversas particulares"}</Render>
{". Recomendamos "}
<Render tag="b" props={{}}>{"desmarcar"}</Render>
{" — nada da conferência depende do chat. "}</Render></Render></Render>
<Render tag="app-ui-accordion-tab" props={{"header": "3. O que fazer durante a gravação"}}><Render tag="p" props={{"className": ["mt-0 line-height-3"].filter(Boolean).join(' ')}}>{" Tudo numa "}
<Render tag="b" props={{}}>{"gravação só"}</Render>
{". As trocas de equipamento ficam registradas com a hora, então dá para separar as fases depois — o que importa é comparar o mesmo personagem com e sem cada peça. "}</Render>
<Render tag="ol" props={{"className": ["mt-0 line-height-3"].filter(Boolean).join(' ')}}><Render tag="li" props={{}}>{"Vá ao "}
<Render tag="b" props={{}}>{"campo de treinamento"}</Render>
{" ("}
<Render tag="code" props={{}}>{"tra_fild"}</Render>
{"), fique de frente para um "}
<Render tag="b" props={{}}>{"dummy"}</Render>
{" e comece a gravar."}</Render>
<Render tag="li" props={{}}><Render tag="b" props={{}}>{"Espere seus buffs de fora acabarem"}</Render>
{" antes de bater — ou vá para o campo sem eles."}</Render>
<Render tag="li" props={{}}><Render tag="b" props={{}}>{"Sem nenhum equipamento:"}</Render>
{" use cada habilidade de ataque umas 10 vezes (as repetições garantem críticos, que é o que dá para conferir com precisão)."}</Render>
<Render tag="li" props={{}}><Render tag="b" props={{}}>{"Só com a arma:"}</Render>
{" repita as mesmas habilidades."}</Render>
<Render tag="li" props={{}}><Render tag="b" props={{}}>{"Com o equipamento completo:"}</Render>
{" repita de novo."}</Render>
<Render tag="li" props={{}}>{"Use a "}
<Render tag="b" props={{}}>{"habilidade suprema"}</Render>
{", ainda no dummy."}</Render>
<Render tag="li" props={{}}><Render tag="b" props={{}}>{"Saia do campo e volte, uma vez, ainda gravando."}</Render>
{" É ao entrar num mapa que o jogo grava seus "}
<Render tag="b" props={{}}>{"talentos"}</Render>
{" no arquivo — sem isso eles não vão junto e o formulário vai pedir que você os digite. Comece a gravar "}
<Render tag="b" props={{}}>{"já dentro do campo"}</Render>
{": a gravação é recusada se o mapa onde ela começa não for o "}
<Render tag="code" props={{}}>{"tra_fild"}</Render>
{". "}</Render>
<Render tag="li" props={{}}>{"Não mexa nos "}
<Render tag="b" props={{}}>{"talentos"}</Render>
{" durante a gravação."}</Render></Render>
<Render tag="p" props={{"className": ["mt-0 line-height-3"].filter(Boolean).join(' ')}}>{" Se quiser ajudar mais, repita a sequência nos dummies de "}
<Render tag="b" props={{}}>{"tamanhos"}</Render>
{" e "}
<Render tag="b" props={{}}>{"elementos"}</Render>
{" diferentes — eles ficam no mesmo campo, e é assim que dá para conferir os bônus por tamanho e por elemento. "}</Render>
<Render tag="ul" props={{"className": ["mt-0 line-height-3"].filter(Boolean).join(' ')}}><Render tag="li" props={{}}>{"Só gravações do "}
<Render tag="b" props={{}}>{"RO LATAM"}</Render>
{" — o arquivo não diz de qual servidor veio, então isso fica na sua palavra."}</Render>
<Render tag="li" props={{}}>{"Um personagem por gravação, e poucos minutos (o limite é 900 KB)."}</Render>
<Render tag="li" props={{}}>{" Bater em monstros de verdade fica para uma etapa seguinte: enquanto os itens e as fórmulas não estiverem certos no dummy, não há como interpretar o que acontece fora dele. "}</Render></Render></Render></Render>
{(() => { const __condition1 = !(vm.sentId);  return __condition1 ? <><Render tag="div" props={{"tabIndex": "0",
"dragover": (event: any) => vm.action(() => { const $event = event; vm.onDragOver($event) }),
"dragleave": (event: any) => vm.action(() => { const $event = event; vm.onDragLeave($event) }),
"drop": (event: any) => vm.action(() => { const $event = event; vm.onDrop($event) }),
"click": (event: any) => vm.action(() => { const $event = event; vm.replayInput.click() }),
"keydown": (event: any) => vm.action(() => { const $event = event; if (event.key?.toLowerCase() === "enter") { vm.replayInput.click() } }),
"className": ["replay-dropzone mt-3",(vm.dragOver ? "dragover" : '')].filter(Boolean).join(' ')}}>{(() => { let replayInput: any = vm["replayInput"]; return <><Render tag="app-icon" props={{"name": "upload",
"className": ["replay-dropzone-icon"].filter(Boolean).join(' ')}}></Render>
<Render tag="p" props={{"className": ["m-0"].filter(Boolean).join(' ')}}>{"Arraste sua gravação "}
<Render tag="b" props={{}}>{".rrf"}</Render>
{" aqui"}</Render>
<Render tag="p" props={{"className": ["my-2 text-sm"].filter(Boolean).join(' ')}}>{"ou"}</Render>
<Render tag="button" props={{"type": "button",
"icon": "folder-open",
"label": "Selecionar arquivo",
"click": (event: any) => vm.action(() => { const $event = event; $event.stopPropagation();replayInput.click() }),
"className": ["ui-button-sm ui-button-outlined"].filter(Boolean).join(' '),
"button": true}}></Render>
<Render tag="input" props={{"type": "file",
"accept": ".rrf",
"hidden": true,
"change": (event: any) => vm.action(() => { const $event = event; vm.onInputChange($event) }),
"reference": (value: any) => { replayInput = value; vm["replayInput"] = value; }}}></Render></>; })()}</Render></> : null; })()}
{(() => { const __condition2 = vm.parsing;  return __condition2 ? <><Render tag="div" props={{"className": ["mt-3 text-center"].filter(Boolean).join(' ')}}><Render tag="app-icon" props={{"name": "spinner",
"className": ["mr-2"].filter(Boolean).join(' ')}}></Render>
{"Conferindo a gravação…"}</Render></> : null; })()}
{(() => { const __condition3 = vm.rejected; const bad = __condition3; return __condition3 ? <><Render tag="div" props={{"className": ["mt-3 p-3 border-round line-height-3"].filter(Boolean).join(' '),
"style": normalizeStyle(Object.assign({}, parseStyle("background: var(--red-100); color: var(--red-900)")))}}><Render tag="div" props={{"className": ["flex align-items-start gap-2"].filter(Boolean).join(' ')}}><Render tag="app-icon" props={{"name": "times-circle",
"className": ["mt-1"].filter(Boolean).join(' ')}}></Render>
<Render tag="div" props={{}}><Render tag="b" props={{}}>{"Essa gravação não serve."}</Render>
<Render tag="div" props={{"className": ["mt-1"].filter(Boolean).join(' ')}}>{interpolate(["",""], [bad.message])}</Render></Render></Render></Render></> : null; })()}
{(() => { const __condition4 = vm.accepted; const good = __condition4; return __condition4 ? <><>{(() => { const __condition5 = !(vm.sentId);  return __condition5 ? <><Render tag="div" props={{"className": ["mt-3"].filter(Boolean).join(' ')}}><Render tag="h3" props={{"className": ["mt-0 mb-2 text-lg"].filter(Boolean).join(' ')}}>{"Confira se é isso mesmo"}</Render>
<Render tag="div" props={{"className": ["submission-summary p-3 border-round surface-100"].filter(Boolean).join(' ')}}><Render tag="div" props={{}}><Render tag="span" props={{}}>{"Personagem"}</Render>
<Render tag="b" props={{}}>{interpolate(["",""], [(good.summary.player || "—")])}</Render></Render>
<Render tag="div" props={{}}><Render tag="span" props={{}}>{"Classe"}</Render>
<Render tag="b" props={{}}>{interpolate(["",""], [good.summary.className])}</Render></Render>
<Render tag="div" props={{}}><Render tag="span" props={{}}>{"Nível"}</Render>
<Render tag="b" props={{}}>{interpolate([""," / ",""], [good.summary.baseLevel,good.summary.jobLevel])}</Render></Render>
<Render tag="div" props={{}}><Render tag="span" props={{}}>{"Mapa"}</Render>
<Render tag="b" props={{}}>{interpolate(["",""], [(good.summary.map || "—")])}</Render></Render>
<Render tag="div" props={{}}><Render tag="span" props={{}}>{"Duração"}</Render>
<Render tag="b" props={{}}>{interpolate(["",""], [vm.formatDuration(good.summary.durationMs)])}</Render></Render>
<Render tag="div" props={{}}><Render tag="span" props={{}}>{"Habilidades"}</Render>
<Render tag="b" props={{}}>{interpolate(["",""], [good.summary.learnedSkillCount])}</Render></Render>
<Render tag="div" props={{}}><Render tag="span" props={{}}>{"Equipamentos"}</Render>
<Render tag="b" props={{}}>{interpolate(["",""], [good.summary.equippedCount])}</Render></Render>
<Render tag="div" props={{}}><Render tag="span" props={{}}>{"Trocas de equip."}</Render>
<Render tag="b" props={{}}>{interpolate(["",""], [good.summary.equipChangeCount])}</Render></Render>
<Render tag="div" props={{}}><Render tag="span" props={{}}>{"Golpes gravados"}</Render>
<Render tag="b" props={{}}>{interpolate(["",""], [good.summary.damageEvents])}</Render></Render>
<Render tag="div" props={{}}><Render tag="span" props={{}}>{"Golpes nos dummies"}</Render>
<Render tag="b" props={{}}>{interpolate(["",""], [good.summary.dummyHits])}</Render></Render>
{(() => { const __condition6 = good.summary.skippedItems.length;  return __condition6 ? <><Render tag="div" props={{}}><Render tag="span" props={{}}>{"Itens fora do banco"}</Render>
<Render tag="b" props={{}}>{interpolate(["",""], [good.summary.skippedItems.length])}</Render></Render></> : null; })()}
{(() => { const __condition7 = vm.importedTraits; const t = __condition7; return __condition7 ? <><Render tag="div" props={{}}><Render tag="span" props={{}}>{"Talentos"}</Render>
<Render tag="b" props={{}}>{(vm.traitKeys ?? []).map((__entry8: any, __index8: number, __array8: any[]) => { const key = __entry8;
const last = __index8 === __array8.length - 1; return <Fragment key={identityKey(__entry8)}><>{interpolate([""," ",""], [vm.traitLabels[key],t[key]])}
{(() => { const __condition9 = !(last);  return __condition9 ? <><Render tag="span" props={{}}>{" · "}</Render></> : null; })()}</></Fragment>; })}</Render></Render></> : null; })()}</Render>
{(() => { const __condition10 = good.warnings.length;  return __condition10 ? <><Render tag="div" props={{"className": ["mt-2 p-2 border-round line-height-3"].filter(Boolean).join(' '),
"style": normalizeStyle(Object.assign({}, parseStyle("background: var(--yellow-100); color: var(--yellow-900)")))}}>{(() => { const __condition11 = good.warnings.includes("external-buffs");  return __condition11 ? <><Render tag="div" props={{}}><Render tag="app-icon" props={{"name": "exclamation-triangle",
"className": ["mr-1"].filter(Boolean).join(' ')}}></Render>
{"A gravação tem "}
<Render tag="b" props={{}}>{"buffs de fora"}</Render>
{" ligados (Bênção, Agilidade, Bragi e parecidos). Ela ainda vai ser lida, mas eles inflam todos os números sem dizer em que etapa entraram — uma gravação sem eles vale bem mais. "}</Render></> : null; })()}
{(() => { const __condition12 = good.warnings.includes("no-equip-change");  return __condition12 ? <><Render tag="div" props={{}}><Render tag="app-icon" props={{"name": "exclamation-triangle",
"className": ["mr-1"].filter(Boolean).join(' ')}}></Render>
{"Você não trocou de equipamento durante a gravação. Ela ainda ajuda, mas a comparação fica bem mais fácil com as fases “sem equipamento / só arma / completo”. "}</Render></> : null; })()}
{(() => { const __condition13 = good.warnings.includes("many-unknown-items");  return __condition13 ? <><Render tag="div" props={{}}><Render tag="app-icon" props={{"name": "exclamation-triangle",
"className": ["mr-1"].filter(Boolean).join(' ')}}></Render>
{"Vários itens não estão no nosso banco. Se a gravação for mesmo do LATAM, ótimo — é justamente o tipo de coisa que precisamos cadastrar. "}</Render></> : null; })()}</Render></> : null; })()}
{(() => { const __condition14 = good.needsTraits;  return __condition14 ? <><Render tag="div" props={{"className": ["mt-3"].filter(Boolean).join(' ')}}><Render tag="h3" props={{"className": ["mt-0 mb-1 text-lg"].filter(Boolean).join(' ')}}>{"Seus talentos"}</Render>
<Render tag="p" props={{"className": ["mt-0 mb-2 line-height-3 text-sm"].filter(Boolean).join(' ')}}>{" Esta gravação "}
<Render tag="b" props={{}}>{"não"}</Render>
{" trouxe os talentos, e sem eles o teste dá errado. O jogo só os grava quando o personagem "}
<Render tag="b" props={{}}>{"entra num mapa"}</Render>
{", e esta ficou o tempo todo parada no mesmo lugar. Da próxima vez eles vêm sozinhos se você "}
<Render tag="b" props={{}}>{"começar a gravar já no campo de treinamento, sair dele e voltar"}</Render>
{" — a volta é a entrada no mapa que os registra. Por ora, abra a janela de status e copie o "}
<Render tag="b" props={{}}>{"primeiro número"}</Render>
{" de cada um — "}
<Render tag="b" props={{}}>{"sem"}</Render>
{" o valor entre parênteses, que é o bônus de classe. Em "}
<Render tag="span" props={{"className": ["font-italic"].filter(Boolean).join(' ')}}>{"POD 90 (+15)"}</Render>
{", o que vale aqui é "}
<Render tag="b" props={{}}>{"90"}</Render>
{". "}</Render>
<Render tag="div" props={{"className": ["trait-grid"].filter(Boolean).join(' ')}}>{(vm.traitKeys ?? []).map((__entry15: any, __index15: number, __array15: any[]) => { const key = __entry15; return <Fragment key={identityKey(__entry15)}><Render tag="app-status-input" props={{"label": vm.traitLabels[key],
"dropdownList": vm.traitStatusList,
"value": vm.traits[key],
"showExtra": false,
"valueChange": (event: any) => vm.action(() => { const $event = event; (vm.traits[key] = $event) })}}></Render></Fragment>; })}</Render>
{(() => { const __condition16 = vm.traitsUntouched;  return __condition16 ? <><Render tag="div" props={{"className": ["mt-2 p-2 border-round line-height-3 text-sm"].filter(Boolean).join(' '),
"style": normalizeStyle(Object.assign({}, parseStyle("background: var(--yellow-100); color: var(--yellow-900)")))}}><Render tag="app-icon" props={{"name": "exclamation-triangle",
"className": ["mr-1"].filter(Boolean).join(' ')}}></Render>
{"Os seis talentos estão em zero. Preencha com os valores da sua janela de status — uma gravação com talentos errados leva a conferência para o lado errado. "}</Render></> : null; })()}</Render></> : null; })()}
<Render tag="h3" props={{"className": ["mt-3 mb-2 text-lg"].filter(Boolean).join(' ')}}>{"Sobre você (opcional)"}</Render>
<Render tag="div" props={{"className": ["grid"].filter(Boolean).join(' ')}}><Render tag="div" props={{"className": ["col-6"].filter(Boolean).join(' ')}}><Render tag="label" props={{"htmlFor": "helpImproveNick",
"className": ["block mb-1 text-sm"].filter(Boolean).join(' ')}}>{"Nick para os créditos"}</Render>
<Render tag="input" props={{"id": "helpImproveNick",
"maxLength": "40",
"placeholder": "como você quer ser citado",
"value": vm.nick,
"onModelChange": (value: any, event: any) => vm.action(() => { ((event: any) => vm.action(() => { const $event = event; (vm.nick = $event) }))(value); }),
"className": ["w-full"].filter(Boolean).join(' '),
"inputText": true}}></Render></Render>
<Render tag="div" props={{"className": ["col-6"].filter(Boolean).join(' ')}}><Render tag="label" props={{"htmlFor": "helpImproveDiscord",
"className": ["block mb-1 text-sm"].filter(Boolean).join(' ')}}>{"Discord"}</Render>
<Render tag="input" props={{"id": "helpImproveDiscord",
"maxLength": "60",
"placeholder": "caso a gente precise perguntar algo",
"value": vm.discord,
"onModelChange": (value: any, event: any) => vm.action(() => { ((event: any) => vm.action(() => { const $event = event; (vm.discord = $event) }))(value); }),
"className": ["w-full"].filter(Boolean).join(' '),
"inputText": true}}></Render></Render>
<Render tag="div" props={{"className": ["col-12"].filter(Boolean).join(' ')}}><Render tag="label" props={{"htmlFor": "helpImproveNotes",
"className": ["block mb-1 text-sm"].filter(Boolean).join(' ')}}>{"O que você gravou / o que achou estranho (opcional)"}</Render>
<Render tag="textarea" props={{"appInputTextarea": "",
"id": "helpImproveNotes",
"rows": "3",
"maxLength": "1000",
"placeholder": "ex.: usei Implosão Tóxica nível 5 no dummy; o dano no jogo parece uns 10% maior que aqui",
"value": vm.notes,
"onModelChange": (value: any, event: any) => vm.action(() => { ((event: any) => vm.action(() => { const $event = event; (vm.notes = $event) }))(value); }),
"className": ["w-full"].filter(Boolean).join(' ')}}></Render></Render></Render>
<Render tag="div" props={{"className": ["mt-2 flex align-items-start gap-2 p-2 border-round surface-100 line-height-3"].filter(Boolean).join(' ')}}><Render tag="app-ui-checkbox" props={{"inputId": "helpImproveConsent",
"binary": true,
"value": vm.consent,
"onModelChange": (value: any, event: any) => vm.action(() => { ((event: any) => vm.action(() => { const $event = event; (vm.consent = $event) }))(value); })}}></Render>
<Render tag="label" props={{"htmlFor": "helpImproveConsent",
"className": ["text-sm"].filter(Boolean).join(' ')}}>{" Confirmo que esta gravação é do "}
<Render tag="b" props={{}}>{"RO LATAM"}</Render>
{" e autorizo o envio do arquivo para os servidores do LATAM Tools. Ela entra na "}
<Render tag="b" props={{}}>{"fila de conferência sem aparecer publicamente"}</Render>
{". Se for aproveitada, pode virar um "}
<Render tag="b" props={{}}>{"teste no código"}</Render>
{", que é aberto — e aí sim o arquivo fica público junto com o repositório. "}</Render></Render>
{(() => { const __condition17 = vm.sendError;  return __condition17 ? <><Render tag="div" props={{"className": ["mt-2 p-2 border-round line-height-3"].filter(Boolean).join(' '),
"style": normalizeStyle(Object.assign({}, parseStyle("background: var(--red-100); color: var(--red-900)")))}}>{interpolate([" "," "], [vm.sendError])}</Render></> : null; })()}
<Render tag="div" props={{"className": ["mt-3 flex justify-content-end"].filter(Boolean).join(' ')}}><Render tag="button" props={{"disabled": !(vm.canSend),
"icon": (vm.sending ? "spinner" : "send"),
"label": (vm.sending ? "Enviando…" : "Enviar gravação"),
"click": (event: any) => vm.action(() => { const $event = event; vm.send() }),
"className": ["ui-button-success"].filter(Boolean).join(' '),
"button": true}}></Render></Render></Render></> : null; })()}</></> : null; })()}
{(() => { const __condition18 = vm.sentId;  return __condition18 ? <><Render tag="div" props={{"className": ["mt-3 p-3 border-round line-height-3"].filter(Boolean).join(' '),
"style": normalizeStyle(Object.assign({}, parseStyle("background: var(--green-100); color: var(--green-900)")))}}><Render tag="div" props={{"className": ["flex align-items-start gap-2"].filter(Boolean).join(' ')}}><Render tag="app-icon" props={{"name": "check-circle",
"className": ["mt-1"].filter(Boolean).join(' ')}}></Render>
<Render tag="div" props={{}}><Render tag="b" props={{}}>{"Recebido, obrigado!"}</Render>
<Render tag="div" props={{"className": ["mt-1"].filter(Boolean).join(' ')}}>{" A gravação entrou na fila de conferência. Se ela levar a alguma correção, aparece nas Novidades — com o seu nick, se você deixou um. "}</Render>
<Render tag="div" props={{"className": ["mt-1 text-sm"].filter(Boolean).join(' ')}}>{"Código do envio: "}
<Render tag="code" props={{}}>{interpolate(["",""], [vm.sentId])}</Render></Render>
<Render tag="button" props={{"icon": "plus",
"label": "Enviar outra",
"click": (event: any) => vm.action(() => { const $event = event; vm.startAnother() }),
"className": ["ui-button-sm ui-button-text mt-2"].filter(Boolean).join(' '),
"button": true}}></Render></Render></Render></Render></> : null; })()}
</Render></>;
}

// src/app/layout/help-improve/help-improve-dialog.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { firstValueFrom } from 'rxjs';
import { ReplaySubmissionService } from 'src/app/api-services/replay-submission.service';
import { RoService } from 'src/app/api-services/ro.service';
import { SubmissionCheck, validateReplaySubmission } from 'src/app/replay/validate-submission';
import { createNumberDropdownList } from 'src/app/utils/create-number-dropdown-list';
import { snoozeHelpImprove, SNOOZE_DAYS } from './help-improve-snooze';

/** The six trait fields, in the order the game's status window lists them. */
const TRAIT_KEYS = ['pow', 'sta', 'wis', 'spl', 'con', 'crt'] as const;
type TraitKey = (typeof TRAIT_KEYS)[number];

const ZERO_TRAITS: Record<TraitKey, number> = { pow: 0, sta: 0, wis: 0, spl: 0, con: 0, crt: 0 };

@Component({
  selector: 'app-help-improve',
  templateUrl: './help-improve-dialog.component.html',
  styleUrls: ['./help-improve-dialog.component.css'],
})
export class HelpImproveDialogComponent {
  @Input() visible = false;
  @Output() visibleChange = new EventEmitter<boolean>();

  /** Stamped on the submission so a bug report can be tied to a release. */
  @Input() appVersion = '';

  readonly snoozeDays = SNOOZE_DAYS;
  readonly traitKeys = TRAIT_KEYS;
  /** The calculator's own trait range, so the two pickers offer the same values. */
  readonly traitStatusList = createNumberDropdownList({ from: 0, to: 100 });
  readonly traitLabels: Record<TraitKey, string> = {
    pow: 'POD',
    sta: 'STA',
    wis: 'SAB',
    spl: 'FEI',
    con: 'CON',
    crt: 'CRV',
  };

  readonly browikiUrl = 'https://browiki.org/wiki/Replay';
  readonly discordUrl = 'https://discord.gg/JCXTqqWq9Q';

  dontShowAgain = false;

  fileName = '';
  dragOver = false;
  parsing = false;
  check: SubmissionCheck | null = null;

  /** Kept aside so the send doesn't have to re-read the file. */
  private bytes: Uint8Array | null = null;

  traits: Record<TraitKey, number> = { ...ZERO_TRAITS };
  nick = '';
  discord = '';
  notes = '';
  consent = false;

  sending = false;
  sentId = '';
  sendError = '';

  constructor(private roService: RoService, private submissions: ReplaySubmissionService) {}

  get accepted(): SubmissionCheck | null {
    return this.check && this.check.ok ? this.check : null;
  }

  get rejected(): SubmissionCheck | null {
    return this.check && !this.check.ok ? this.check : null;
  }

  /**
   * Every field still at zero on a class that has traits. Any single stat may
   * legitimately be 0, but all six at once means the form was left untouched —
   * and traits nobody filled in would silently wreck the comparison.
   */
  get traitsUntouched(): boolean {
    if (!this.accepted?.needsTraits) return false;
    return TRAIT_KEYS.every((k) => !this.traits[k]);
  }

  get canSend(): boolean {
    return !!this.accepted && this.consent && !this.traitsUntouched && !this.sending && !this.sentId;
  }

  onHide() {
    if (this.dontShowAgain) snoozeHelpImprove();
    this.visible = false;
    this.visibleChange.emit(false);
    this.reset();
  }

  onDragOver(event: DragEvent) {
    event.preventDefault();
    this.dragOver = true;
  }

  onDragLeave(event: DragEvent) {
    event.preventDefault();
    this.dragOver = false;
  }

  onDrop(event: DragEvent) {
    event.preventDefault();
    this.dragOver = false;
    const file = event.dataTransfer?.files?.[0];
    if (file) this.readFile(file);
  }

  onInputChange(event: Event) {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    if (file) this.readFile(file);
    input.value = ''; // allow re-picking the same file
  }

  /** Parses and validates in the browser; nothing is sent until "Enviar". */
  async readFile(file: File) {
    if (this.parsing) return;
    this.parsing = true;
    this.check = null;
    this.sentId = '';
    this.sendError = '';
    this.fileName = file.name;
    try {
      const buf = await file.arrayBuffer();
      const items = await firstValueFrom(this.roService.getItems<Record<number, any>>());
      this.check = validateReplaySubmission(buf, items);
      this.bytes = this.check.ok ? new Uint8Array(buf) : null;
    } catch (e) {
      console.error(e);
      this.check = {
        ok: false,
        blocker: 'unreadable',
        message: 'Não foi possível ler o arquivo.',
        summary: null,
        needsTraits: false,
        warnings: [],
      };
      this.bytes = null;
    } finally {
      this.parsing = false;
    }
  }

  async send() {
    const accepted = this.accepted;
    if (!accepted || !this.bytes || !this.canSend) return;
    this.sending = true;
    this.sendError = '';
    try {
      this.sentId = await this.submissions.submit({
        bytes: this.bytes,
        fileName: this.fileName,
        appVersion: this.appVersion,
        summary: accepted.summary,
        traits: accepted.needsTraits ? this.traits : null,
        nick: this.nick,
        discord: this.discord,
        notes: this.notes,
      });
      // The bytes are the bulk of the memory here and are no longer needed.
      this.bytes = null;
    } catch (e) {
      console.error(e);
      this.sendError = 'Não deu para enviar agora. Tente de novo daqui a pouco — se insistir, avise no Discord.';
    } finally {
      this.sending = false;
    }
  }

  /** Clears the file and the form, but keeps who the person is. */
  startAnother() {
    this.check = null;
    this.bytes = null;
    this.fileName = '';
    this.sentId = '';
    this.sendError = '';
    this.notes = '';
    this.consent = false;
    this.traits = { ...ZERO_TRAITS };
  }

  formatDuration(ms: number): string {
    const total = Math.round(ms / 1000);
    return `${Math.floor(total / 60)}m ${String(total % 60).padStart(2, '0')}s`;
  }

  private reset() {
    this.startAnother();
    this.nick = '';
    this.discord = '';
  }
}

<p-dialog
  [visible]="visible"
  (visibleChange)="!$event && onHide()"
  [modal]="true"
  [draggable]="false"
  [resizable]="false"
  [style]="dialogStyle"
  [contentStyle]="{ maxHeight: '75vh' }"
>
  <ng-template pTemplate="header">
    <div class="flex align-items-center gap-2">
      <i class="pi pi-heart-fill text-xl"></i>
      <span class="text-xl font-medium">Ajude o simulador a acertar as contas</span>
    </div>
  </ng-template>

  <p class="mt-0 line-height-3">
    Cada fórmula daqui é conferida contra o jogo de verdade: pegamos uma <b>gravação</b> sua, lemos os pacotes de dano um por um e
    comparamos com o que o simulador calcula. Quando um número não bate, é assim que o erro aparece — e é assim que ele é corrigido.
  </p>
  <p class="line-height-3">
    Esta primeira etapa tem um alvo específico: <b>achar itens cadastrados errados e fórmulas erradas</b>. Para isso a gravação
    precisa ser <b>limpa</b> — só assim dá para saber se a diferença veio do item ou da conta. Por isso duas regras são obrigatórias, e
    o envio é recusado sem elas:
  </p>
  <div class="flex align-items-start gap-2 mb-3 p-3 border-round" style="background: var(--yellow-100); color: var(--yellow-900)">
    <i class="pi pi-exclamation-triangle mt-1"></i>
    <div class="line-height-3">
      <b>1. No campo de treinamento</b> (<code>tra_fild</code>), <b>batendo nos dummies</b>. Os dummies têm DEF e RES zeradas, ficam
      parados e não revidam — é o único alvo cujos números são todos conhecidos. Em qualquer outro lugar o monstro tem defesas próprias e
      a conta passa a ter duas incógnitas ao mesmo tempo.<br />
      <b>2. Sem buffs de fora.</b> Nada de Bênção, Agilidade, Bragi, Poema, comidas ou buffs de outro jogador. Eles inflam todos os
      números sem dizer em que etapa entraram, e foi exatamente o que inutilizou a primeira leva de gravações. Seus próprios bônus de
      equipamento e as habilidades da sua classe, sim — é isso que está sendo medido.
    </div>
  </div>
  <p class="line-height-3">
    Gravar leva uns <b>10 minutos</b> e ajuda principalmente as classes menos testadas. Se a sua gravação levar a alguma correção, seu
    nome entra nas Novidades.
  </p>

  <p-accordion>
    <p-accordionTab header="1. Como abrir o gravador">
      <ul class="mt-0 line-height-3">
        <li>O gravador fica num botão dentro da <b>janela de informações do personagem</b>.</li>
        <li>Ele tem os botões <b>Início/Fim</b>, <b>Pausa</b> e <b>Opções</b>.</li>
        <li>É preciso dar um <b>nome</b> ao vídeo antes de gravar.</li>
        <li>O arquivo sai em <b>.rrf</b>, na pasta <b>Replay</b> de onde o jogo está instalado.</li>
      </ul>
      <a [href]="browikiUrl" target="_blank" rel="noreferrer noopener">Passo a passo completo no bROWiki →</a>
    </p-accordionTab>

    <p-accordionTab header="2. Antes de apertar Início — confira as Opções">
      <div class="flex align-items-start gap-2 mb-3 p-2 border-round" style="background: var(--yellow-100); color: var(--yellow-900)">
        <i class="pi pi-exclamation-triangle mt-1"></i>
        <div class="line-height-3">
          A caixa <b>Skill</b> é o que põe a <b>árvore de habilidades</b> dentro do arquivo — sem ela não dá para conferir nada, e o envio
          é recusado. As caixas só podem ser mexidas <b>antes</b> de começar a gravar.
        </div>
      </div>
      <ul class="mt-0 line-height-3">
        <li>Marque <b>Basic Info</b>, <b>Equip</b>, <b>Item</b> e <b>Skill</b> — o mais fácil é marcar <b>All</b>.</li>
        <li>
          <b>Privacidade:</b> com <b>Chatting</b> marcado, a gravação leva junto o chat público e as <b>conversas particulares</b>.
          Recomendamos <b>desmarcar</b> — nada da conferência depende do chat.
        </li>
      </ul>
    </p-accordionTab>

    <p-accordionTab header="3. O que fazer durante a gravação">
      <p class="mt-0 line-height-3">
        Tudo numa <b>gravação só</b>. As trocas de equipamento ficam registradas com a hora, então dá para separar as fases depois — o que
        importa é comparar o mesmo personagem com e sem cada peça.
      </p>
      <ol class="mt-0 line-height-3">
        <li>Vá ao <b>campo de treinamento</b> (<code>tra_fild</code>), fique de frente para um <b>dummy</b> e comece a gravar.</li>
        <li><b>Espere seus buffs de fora acabarem</b> antes de bater — ou vá para o campo sem eles.</li>
        <li><b>Sem nenhum equipamento:</b> use cada habilidade de ataque umas 10 vezes (as repetições garantem críticos, que é o que dá para conferir com precisão).</li>
        <li><b>Só com a arma:</b> repita as mesmas habilidades.</li>
        <li><b>Com o equipamento completo:</b> repita de novo.</li>
        <li>Use a <b>habilidade suprema</b>, ainda no dummy.</li>
        <li>
          <b>Saia do campo e volte, uma vez, ainda gravando.</b> É ao entrar num mapa que o jogo grava seus <b>talentos</b> no arquivo —
          sem isso eles não vão junto e o formulário vai pedir que você os digite. Comece a gravar <b>já dentro do campo</b>: a gravação
          é recusada se o mapa onde ela começa não for o <code>tra_fild</code>.
        </li>
        <li>Não mexa nos <b>talentos</b> durante a gravação.</li>
      </ol>
      <p class="mt-0 line-height-3">
        Se quiser ajudar mais, repita a sequência nos dummies de <b>tamanhos</b> e <b>elementos</b> diferentes — eles ficam no mesmo
        campo, e é assim que dá para conferir os bônus por tamanho e por elemento.
      </p>
      <ul class="mt-0 line-height-3">
        <li>Só gravações do <b>RO LATAM</b> — o arquivo não diz de qual servidor veio, então isso fica na sua palavra.</li>
        <li>Um personagem por gravação, e poucos minutos (o limite é 900 KB).</li>
        <li>
          Bater em monstros de verdade fica para uma etapa seguinte: enquanto os itens e as fórmulas não estiverem certos no dummy,
          não há como interpretar o que acontece fora dele.
        </li>
      </ul>
    </p-accordionTab>
  </p-accordion>

  <!-- Drop the file (parsed and checked here, nothing leaves the browser yet) -->
  <div
    *ngIf="!sentId"
    class="replay-dropzone mt-3"
    [class.dragover]="dragOver"
    (dragover)="onDragOver($event)"
    (dragleave)="onDragLeave($event)"
    (drop)="onDrop($event)"
    (click)="replayInput.click()"
    (keydown.enter)="replayInput.click()"
    tabindex="0"
  >
    <i class="pi pi-upload replay-dropzone-icon"></i>
    <p class="m-0">Arraste sua gravação <b>.rrf</b> aqui</p>
    <p class="my-2 text-sm">ou</p>
    <button
      type="button"
      pButton
      class="p-button-sm p-button-outlined"
      icon="pi pi-folder-open"
      label="Selecionar arquivo"
      (click)="$event.stopPropagation(); replayInput.click()"
    ></button>
    <input #replayInput type="file" accept=".rrf" hidden (change)="onInputChange($event)" />
  </div>

  <div *ngIf="parsing" class="mt-3 text-center"><i class="pi pi-spin pi-spinner mr-2"></i>Conferindo a gravação…</div>

  <!-- Rejected: say why, and what to change when recording again -->
  <div
    *ngIf="rejected as bad"
    class="mt-3 p-3 border-round line-height-3"
    style="background: var(--red-100); color: var(--red-900)"
  >
    <div class="flex align-items-start gap-2">
      <i class="pi pi-times-circle mt-1"></i>
      <div>
        <b>Essa gravação não serve.</b>
        <div class="mt-1">{{ bad.message }}</div>
      </div>
    </div>
  </div>

  <!-- Accepted: show what was read, then the rest of the form -->
  <ng-container *ngIf="accepted as good">
    <div *ngIf="!sentId" class="mt-3">
      <h3 class="mt-0 mb-2 text-lg">Confira se é isso mesmo</h3>
      <div class="submission-summary p-3 border-round surface-100">
        <div><span>Personagem</span><b>{{ good.summary.player || '—' }}</b></div>
        <div><span>Classe</span><b>{{ good.summary.className }}</b></div>
        <div><span>Nível</span><b>{{ good.summary.baseLevel }} / {{ good.summary.jobLevel }}</b></div>
        <div><span>Mapa</span><b>{{ good.summary.map || '—' }}</b></div>
        <div><span>Duração</span><b>{{ formatDuration(good.summary.durationMs) }}</b></div>
        <div><span>Habilidades</span><b>{{ good.summary.learnedSkillCount }}</b></div>
        <div><span>Equipamentos</span><b>{{ good.summary.equippedCount }}</b></div>
        <div><span>Trocas de equip.</span><b>{{ good.summary.equipChangeCount }}</b></div>
        <div><span>Golpes gravados</span><b>{{ good.summary.damageEvents }}</b></div>
        <div><span>Golpes nos dummies</span><b>{{ good.summary.dummyHits }}</b></div>
        <div *ngIf="good.summary.skippedItems.length">
          <span>Itens fora do banco</span><b>{{ good.summary.skippedItems.length }}</b>
        </div>
        <!-- Read off the recording itself, so it is shown for conference like everything
             else here — not asked for again below. -->
        <div *ngIf="importedTraits as t">
          <span>Talentos</span>
          <b>
            <ng-container *ngFor="let key of traitKeys; let last = last"
              >{{ traitLabels[key] }} {{ t[key] }}<span *ngIf="!last">&nbsp;·&nbsp;</span></ng-container
            >
          </b>
        </div>
      </div>

      <div *ngIf="good.warnings.length" class="mt-2 p-2 border-round line-height-3" style="background: var(--yellow-100); color: var(--yellow-900)">
        <div *ngIf="good.warnings.includes('external-buffs')">
          <i class="pi pi-exclamation-triangle mr-1"></i>A gravação tem <b>buffs de fora</b> ligados (Bênção, Agilidade, Bragi e
          parecidos). Ela ainda vai ser lida, mas eles inflam todos os números sem dizer em que etapa entraram — uma gravação sem eles
          vale bem mais.
        </div>
        <div *ngIf="good.warnings.includes('no-equip-change')">
          <i class="pi pi-exclamation-triangle mr-1"></i>Você não trocou de equipamento durante a gravação. Ela ainda ajuda, mas a
          comparação fica bem mais fácil com as fases “sem equipamento / só arma / completo”.
        </div>
        <div *ngIf="good.warnings.includes('many-unknown-items')">
          <i class="pi pi-exclamation-triangle mr-1"></i>Vários itens não estão no nosso banco. Se a gravação for mesmo do LATAM, ótimo —
          é justamente o tipo de coisa que precisamos cadastrar.
        </div>
      </div>

      <!-- Traits: only asked for when this particular recording did not carry them.
           The server sends them on every map load, so a session recorded entirely
           inside the training field arrives without any. -->
      <div *ngIf="good.needsTraits" class="mt-3">
        <h3 class="mt-0 mb-1 text-lg">Seus talentos</h3>
        <p class="mt-0 mb-2 line-height-3 text-sm">
          Esta gravação <b>não</b> trouxe os talentos, e sem eles o teste dá errado. O jogo só os grava quando o personagem
          <b>entra num mapa</b>, e esta ficou o tempo todo parada no mesmo lugar. Da próxima vez eles vêm sozinhos se você
          <b>começar a gravar já no campo de treinamento, sair dele e voltar</b> — a volta é a entrada no mapa que os registra.
          Por ora, abra a janela de status e copie o <b>primeiro número</b> de cada um — <b>sem</b> o valor entre parênteses, que é o
          bônus de classe. Em <span class="font-italic">POD 90 (+15)</span>, o que vale aqui é <b>90</b>.
        </p>
        <div class="trait-grid">
          <!-- The calculator's own field (app-status-input), same 0-100 list, so the
               two look and behave alike. No equipment here, hence no "+N" badge. -->
          <app-status-input
            *ngFor="let key of traitKeys"
            [label]="traitLabels[key]"
            [dropdownList]="traitStatusList"
            [(value)]="traits[key]"
            [showExtra]="false"
          ></app-status-input>
        </div>
        <div *ngIf="traitsUntouched" class="mt-2 p-2 border-round line-height-3 text-sm" style="background: var(--yellow-100); color: var(--yellow-900)">
          <i class="pi pi-exclamation-triangle mr-1"></i>Os seis talentos estão em zero. Preencha com os valores da sua janela de status —
          uma gravação com talentos errados leva a conferência para o lado errado.
        </div>
      </div>

      <h3 class="mt-3 mb-2 text-lg">Sobre você (opcional)</h3>
      <div class="grid">
        <div class="col-6">
          <label class="block mb-1 text-sm" for="helpImproveNick">Nick para os créditos</label>
          <input pInputText id="helpImproveNick" class="w-full" maxlength="40" [(ngModel)]="nick" placeholder="como você quer ser citado" />
        </div>
        <div class="col-6">
          <label class="block mb-1 text-sm" for="helpImproveDiscord">Discord</label>
          <input
            pInputText
            id="helpImproveDiscord"
            class="w-full"
            maxlength="60"
            [(ngModel)]="discord"
            placeholder="caso a gente precise perguntar algo"
          />
        </div>
        <div class="col-12">
          <label class="block mb-1 text-sm" for="helpImproveNotes">O que você gravou / o que achou estranho (opcional)</label>
          <textarea
            pInputTextarea
            id="helpImproveNotes"
            class="w-full"
            rows="3"
            maxlength="1000"
            [(ngModel)]="notes"
            placeholder="ex.: usei Implosão Tóxica nível 5 no dummy; o dano no jogo parece uns 10% maior que aqui"
          ></textarea>
        </div>
      </div>

      <div class="mt-2 flex align-items-start gap-2 p-2 border-round surface-100 line-height-3">
        <p-checkbox [(ngModel)]="consent" [binary]="true" inputId="helpImproveConsent"></p-checkbox>
        <label for="helpImproveConsent" class="text-sm">
          Confirmo que esta gravação é do <b>RO LATAM</b> e autorizo o envio do arquivo para os servidores do LATAM Tools. Ela entra na
          <b>fila de conferência sem aparecer publicamente</b>. Se for aproveitada, pode virar um <b>teste no código</b>, que é aberto — e aí
          sim o arquivo fica público junto com o repositório.
        </label>
      </div>

      <div *ngIf="sendError" class="mt-2 p-2 border-round line-height-3" style="background: var(--red-100); color: var(--red-900)">
        {{ sendError }}
      </div>

      <div class="mt-3 flex justify-content-end">
        <button
          pButton
          class="p-button-success"
          [disabled]="!canSend"
          [icon]="sending ? 'pi pi-spin pi-spinner' : 'pi pi-send'"
          [label]="sending ? 'Enviando…' : 'Enviar gravação'"
          (click)="send()"
        ></button>
      </div>
    </div>
  </ng-container>

  <!-- Sent -->
  <div *ngIf="sentId" class="mt-3 p-3 border-round line-height-3" style="background: var(--green-100); color: var(--green-900)">
    <div class="flex align-items-start gap-2">
      <i class="pi pi-check-circle mt-1"></i>
      <div>
        <b>Recebido, obrigado!</b>
        <div class="mt-1">
          A gravação entrou na fila de conferência. Se ela levar a alguma correção, aparece nas Novidades — com o seu nick, se você deixou
          um.
        </div>
        <div class="mt-1 text-sm">Código do envio: <code>{{ sentId }}</code></div>
        <button pButton class="p-button-sm p-button-text mt-2" icon="pi pi-plus" label="Enviar outra" (click)="startAnother()"></button>
      </div>
    </div>
  </div>

  <ng-template pTemplate="footer">
    <div class="flex align-items-center justify-content-between w-full">
      <div class="flex align-items-center gap-2">
        <p-checkbox [(ngModel)]="dontShowAgain" [binary]="true" inputId="helpImproveSnooze"></p-checkbox>
        <label for="helpImproveSnooze" class="text-sm">Não mostrar de novo pelos próximos {{ snoozeDays }} dias</label>
      </div>
      <button pButton class="p-button-text" label="Fechar" (click)="onHide()"></button>
    </div>
  </ng-template>
</p-dialog>
